// Product catalogues and the plain lookups over them. Prices live here only.
import type {
  Ap,
  Cam,
  CableSpec,
  CondTemplate,
  InfraItem,
  Item,
  Junction,
  Model,
  PipeSpec,
  Shop,
  WanSpec,
} from "./types";
import { t } from "./i18n";

// ---------- Catalog (EUR incl. VAT, UI EU Store / Geizhals, as of 09/2026; ca. where not listed) ----------
// Bilingual fields are { de, en } and go through tx().
// `amazon:` is a verified /dp/<ASIN> link, as of 09/2026 — Amazon swaps ASINs
// out when a listing disappears; verify instead of guessing when unsure.
// `amazonSimilar: true` means: not the original item, but an equivalent substitute.
export const CAMS: Record<string, Cam> = {
  "g6-bullet": {
    name: "G6 Bullet",
    img: "https://cdn.ecomm.ui.com/products/5dc40311-0e08-4eaa-b901-472cc707b436/4dee8c08-78b7-418f-ab85-01329267c062.png",
    amazon: "https://www.amazon.de/dp/B0FRB6F3B3",
    url: "physical-security-bullet/products/uvc-g6-bullet",
    price: 179,
    res: '4K · 8 MP · 1/1.8"',
    ir: 30,
    fov: 106,
    poe: "PoE (802.3af)",
    ip: "IP66",
    out: true,
    note: {
      de: "Standard für außen. Bestes Preis/Leistung, 30 m Nachtsicht, AI-Erkennung.",
      en: "The outdoor default. Best value, 30 m night vision, AI detection.",
    },
    tags: { de: ["4K", "außen", "IR 30 m"], en: ["4K", "outdoor", "IR 30 m"] },
  },
  "g6-turret": {
    name: "G6 Turret",
    img: "https://cdn.ecomm.ui.com/products/cc0e6f23-b53b-45b5-bff5-faf69f4fbf30/40f697ee-d5c1-4e96-b418-1c642ab1ea19.png",
    amazon: "https://www.amazon.de/dp/B0F81MRNMC",
    url: "physical-security-turret/products/uvc-g6-turret",
    price: 179,
    res: '4K · 8 MP · 1/1.8"',
    ir: 30,
    fov: 106,
    poe: "PoE (802.3af)",
    ip: "IP66",
    out: true,
    note: {
      de: "Gleiche Technik wie Bullet, für Decken- und Unterzugmontage (Stallgasse, Vordach).",
      en: "Same internals as the Bullet, for ceiling and soffit mounting (stable aisle, porch roof).",
    },
    tags: { de: ["4K", "Decke", "IR 30 m"], en: ["4K", "ceiling", "IR 30 m"] },
  },
  "g6-dome": {
    name: "G6 Dome",
    img: "https://cdn.ecomm.ui.com/products/2f241968-e3be-42c2-98fc-7d879b360d25/1e661d71-79eb-4f79-9f17-2199b3655bb4.png",
    amazon: "https://www.amazon.de/dp/B0FJZV8282",
    url: "physical-security-dome/products/uvc-g6-dome",
    price: 249,
    res: '4K · 8 MP · 1/1.8"',
    ir: 30,
    fov: 106,
    poe: "PoE (802.3af)",
    ip: "IP66 · IK10",
    out: false,
    note: {
      de: "Vandalensicher. Nur sinnvoll, wo jemand rankommt und zuschlagen kann.",
      en: "Vandal resistant. Only worth it where someone can reach it and take a swing.",
    },
    tags: { de: ["4K", "IK10"], en: ["4K", "IK10"] },
  },
  "g6-180": {
    name: "G6 180",
    img: "https://cdn.ecomm.ui.com/products/c2196251-739c-43d0-b840-567a732cd7ef/cc48eefc-2995-4d40-add0-7a36f9e2325e.png",
    amazon: "https://www.amazon.de/dp/B0H75W7CNL",
    url: "physical-security-panoramic/products/uvc-g6-180",
    price: 269,
    res: "2× 8 MP (16 MP) Dual-Sensor",
    ir: 20,
    fov: 180,
    poe: "PoE+ (802.3at)",
    ip: "IP66",
    out: true,
    note: {
      de: "180° Panorama ohne Verzerrung. Übersicht über Hof und Wiese, aber nur 20 m IR und keine Identifikation auf Distanz.",
      en: "180° panorama without distortion. Good overview of yard and paddock, but only 20 m IR and no identification at distance.",
    },
    tags: { de: ["180°", "Übersicht", "IR 20 m"], en: ["180°", "overview", "IR 20 m"] },
  },
  "g6-ptz": {
    name: "G6 PTZ",
    img: "https://cdn.ecomm.ui.com/products/8b0777b6-851e-45f8-b4d2-b98b598c1ebc/117bc92a-0154-43fe-9db4-59ba8be2ed3f.png",
    amazon: "https://www.amazon.de/dp/B0FPDH5WXG",
    url: "physical-security-ptz/products/uvc-g6-ptz",
    price: 359,
    res: "4K · 8 MP · 10× optischer Zoom",
    ir: 30,
    fov: 360,
    poe: "PoE+ (802.3at)",
    ip: "IP66",
    out: true,
    note: {
      de: "Schwenkt, zoomt und verfolgt Personen automatisch. Für große Flächen, sieht aber immer nur dahin, wo sie gerade guckt.",
      en: "Pans, zooms and auto-tracks people. Made for large areas, but only ever sees where it happens to be pointing.",
    },
    tags: { de: ["PTZ", "Tracking", "10× Zoom"], en: ["PTZ", "tracking", "10× zoom"] },
  },
  "g6-pro-bullet": {
    name: "G6 Pro Bullet",
    img: "https://cdn.ecomm.ui.com/products/c48d3ada-c223-4a2b-98f3-2bb55c3b1a11/69792922-3944-41ab-a386-2059b23a6b1b.png",
    amazon: "https://www.amazon.de/dp/B0G1PLGDJ5",
    url: "physical-security-bullet/products/uvc-g6-pro-bullet",
    price: 429,
    res: '4K · 1/1.2" · 2,36× Zoom',
    ir: 40,
    fov: 83,
    poe: "PoE+ (802.3at)",
    ip: "IP66",
    out: true,
    note: {
      de: "Großer Sensor, deutlich besser bei Nacht, 40 m IR. Für den Punkt, an dem du ein Gesicht brauchst (Tor, Zufahrt).",
      en: "Large sensor, much better at night, 40 m IR. For the one spot where you need a face (gate, driveway).",
    },
    tags: { de: ["4K", "Pro", "IR 40 m"], en: ["4K", "pro", "IR 40 m"] },
  },
  "g5-bullet": {
    name: "G5 Bullet",
    img: "https://cdn.ecomm.ui.com/products/48ca8dea-109e-4d35-af46-b7ad03764207/0cd9d5ff-af60-45bd-a01f-b0fb050e76bb.png",
    amazon: "https://www.amazon.de/dp/B0BWNLTTGF",
    url: "physical-security-bullet/products/uvc-g5-bullet",
    price: 129,
    res: "2K · 5 MP",
    ir: 30,
    fov: 102,
    poe: "PoE (802.3af)",
    ip: "IP66",
    out: true,
    note: {
      de: "Vorgängergeneration, 2K reicht für Übersicht. Zählt beim NVR nicht als 4K.",
      en: "Previous generation, 2K is fine for overview. Does not count as 4K against the NVR budget.",
    },
    tags: { de: ["2K", "günstig"], en: ["2K", "cheap"] },
  },
  "g5-turret-ultra": {
    name: "G5 Turret Ultra",
    img: "https://cdn.ecomm.ui.com/products/54f9bb29-40b8-4dac-9b1c-7ccf0e303aa5/4291a8f4-7390-4bb6-9190-8953739a0a92.png",
    amazon: "https://www.amazon.de/dp/B0CZ9Q8J8C",
    url: "physical-security-turret/products/uvc-g5-turret-ultra",
    price: 99,
    res: "2K · 4 MP",
    ir: 15,
    fov: 102,
    poe: "PoE (802.3af)",
    ip: "IP66",
    out: false,
    note: {
      de: "Kleinste und günstigste PoE-Kamera. Innen im Stall oder an Nebengebäuden völlig ausreichend.",
      en: "Smallest and cheapest PoE camera. Plenty for inside the stable or on outbuildings.",
    },
    tags: { de: ["2K", "kompakt", "IR 15 m"], en: ["2K", "compact", "IR 15 m"] },
  },
  "g6-instant": {
    name: "G6 Instant (WLAN)",
    img: "https://cdn.ecomm.ui.com/products/16382cd9-95ca-4c26-ae58-3f2cf02c8b75/ac0e2657-769a-4921-ab11-c4eaa9584c13.png",
    amazon: "https://www.amazon.de/dp/B0FD8BQF36",
    url: "physical-security-instant/products/uvc-g6-ins",
    price: 159,
    res: "4K · 8 MP",
    ir: 6,
    fov: 106,
    poe: { de: "USB-C Netzteil, WLAN", en: "USB-C power supply, Wi-Fi" },
    ip: "IP65",
    out: false,
    wifi: true,
    note: {
      de: "Ohne Kabel, dafür abhängig vom WLAN und nur 6 m IR. Nur für Stellen, an die wirklich kein Kabel kommt.",
      en: "No cable, but it depends on Wi-Fi and has only 6 m IR. Only for spots no cable can reach.",
    },
    tags: { de: ["WLAN", "kein PoE", "IR 6 m"], en: ["Wi-Fi", "no PoE", "IR 6 m"] },
  },
  // --- Reolink (ONVIF/RTSP; can be added to UniFi Protect as a third-party camera) ---
  "reolink-rlc-810a": {
    vendor: "reolink",
    name: "Reolink RLC-810A",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2025/04/170301331744858893.3765.jpg.webp",
    amazon: "https://www.amazon.de/dp/B08F7C37NZ",
    url: "https://reolink.com/product/rlc-810a/",
    price: 80,
    res: '4K · 8 MP · 1/2.7"',
    ir: 30,
    fov: 87,
    poe: "PoE (802.3af)",
    ip: "IP67",
    out: true,
    note: {
      de: "Klassische Bullet für Einfahrt oder Grundstücksgrenze — der günstige 4K-PoE-Einstieg.",
      en: "Classic bullet for the driveway or property line — the affordable 4K PoE entry.",
    },
    tags: { de: ["4K", "außen", "IR 30 m", "ONVIF"], en: ["4K", "outdoor", "IR 30 m", "ONVIF"] },
  },
  "reolink-rlc-820a": {
    vendor: "reolink",
    name: "Reolink RLC-820A",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2025/04/210113411745198021.3897.jpg.webp",
    amazon: "https://www.amazon.de/dp/B08KG289Q4",
    url: "https://reolink.com/product/rlc-820a/",
    price: 80,
    res: '4K · 8 MP · 1/2.7"',
    ir: 30,
    fov: 87,
    poe: "PoE (802.3af)",
    ip: "IP67",
    out: true,
    note: {
      de: "Gleiche Technik wie die 810A im Dome-Gehäuse, für Fassade oder Dachüberstand.",
      en: "Same internals as the 810A in a dome housing, for facade or eaves.",
    },
    tags: { de: ["4K", "Decke", "IR 30 m", "ONVIF"], en: ["4K", "ceiling", "IR 30 m", "ONVIF"] },
  },
  "reolink-rlc-842a": {
    vendor: "reolink",
    name: "Reolink RLC-842A",
    img: "https://home-cdn.reolink.us/wp-content/assets/ogimage/rlc-842a-facebook.jpg",
    amazon: "https://www.amazon.de/dp/B09DKMWK68",
    url: "https://reolink.com/product/rlc-842a/",
    price: 120,
    res: '4K · 8 MP · 1/2.8"',
    ir: 30,
    fov: 105,
    poe: "PoE (802.3af)",
    ip: "IP66 · IK10",
    out: true,
    zoom: "5× optisch",
    note: {
      de: "Motorisiertes Varifokal (105°–31°) und IK10. Zum Heranholen von Kennzeichen oder Zufahrt.",
      en: "Motorised varifocal (105°–31°) and IK10. For pulling in plates or the driveway.",
    },
    tags: { de: ["4K", "5× Zoom", "IK10", "ONVIF"], en: ["4K", "5× zoom", "IK10", "ONVIF"] },
  },
  "reolink-duo-3-poe": {
    vendor: "reolink",
    name: "Reolink Duo 3 PoE",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2024/01/030826541704270414.65.png",
    amazon: "https://www.amazon.de/dp/B0CM34VG3X",
    url: "https://reolink.com/product/reolink-duo-3-poe/",
    price: 175,
    res: '16 MP · Dual-Sensor · 2× 1/2.7"',
    ir: 30,
    fov: 180,
    poe: "PoE (802.3af)",
    ip: "IP67",
    out: true,
    note: {
      de: "180° aus zwei Objektiven ohne sichtbare Naht. Für lange Grenzen oder große Höfe.",
      en: "180° from two lenses with no visible seam. For long boundaries or big yards.",
    },
    tags: {
      de: ["180°", "Übersicht", "IR 30 m", "ONVIF"],
      en: ["180°", "overview", "IR 30 m", "ONVIF"],
    },
  },
  "reolink-trackmix-poe": {
    vendor: "reolink",
    name: "Reolink TrackMix PoE",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2025/04/290627131745908033.9896.jpg.webp",
    amazon: "https://www.amazon.de/dp/B0B4KCDD1F",
    url: "https://reolink.com/product/reolink-trackmix-poe/",
    price: 144,
    res: "4K · 8 MP · Weitwinkel + Tele",
    ir: 30,
    fov: 104,
    poe: "PoE (802.3af)",
    ip: "IP65",
    out: true,
    zoom: "6× hybrid",
    note: {
      de: "Weitwinkel und Tele gleichzeitig, verfolgt Objekte automatisch. Für Zufahrten mit Bewegung auf Distanz.",
      en: "Wide and tele at once, tracks objects automatically. For driveways with movement at distance.",
    },
    tags: {
      de: ["4K", "Tracking", "IR 30 m", "ONVIF"],
      en: ["4K", "tracking", "IR 30 m", "ONVIF"],
    },
  },
  "reolink-rlc-823s2": {
    vendor: "reolink",
    name: "Reolink RLC-823S2",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2024/01/240124211706059461.2678.png",
    amazon: "https://www.amazon.de/dp/B0CQLV9QYX",
    url: "https://reolink.com/product/rlc-823s2/",
    price: 320,
    res: "4K · 8 MP · 16× optischer Zoom",
    ir: 80,
    fov: 360,
    poe: "PoE+ (802.3at)",
    ip: "IP66",
    out: true,
    zoom: "16× optisch",
    note: {
      de: "Echtes PTZ: 360°, 16× Zoom, 80 m Nachtsicht. Für weite Flächen — sieht aber nur dahin, wo sie gerade guckt.",
      en: "True PTZ: 360°, 16× zoom, 80 m night vision. For wide areas — but only sees where it is pointing.",
    },
    tags: {
      de: ["PTZ", "16× Zoom", "IR 80 m", "ONVIF"],
      en: ["PTZ", "16× zoom", "IR 80 m", "ONVIF"],
    },
  },
  "reolink-rlc-810wa": {
    vendor: "reolink",
    name: "Reolink RLC-810WA",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2023/09/071011481694081508.6816.jpg.webp",
    amazon: "https://www.amazon.de/dp/B0C8M84Q9W",
    url: "https://reolink.com/product/rlc-810wa/",
    price: 85,
    res: '4K · 8 MP · 1/2.7"',
    ir: 30,
    fov: 89,
    poe: "kein PoE · WLAN (Wi-Fi 6)",
    ip: "IP67",
    out: true,
    wifi: true,
    note: {
      de: "4K ohne Netzwerkkabel dank Wi-Fi 6, braucht aber Steckdose. Nebeneingang, Gartenhaus.",
      en: "4K without a network cable thanks to Wi-Fi 6, but needs a socket. Side entrance, garden shed.",
    },
    tags: { de: ["4K", "WLAN", "kein PoE", "IR 30 m"], en: ["4K", "Wi-Fi", "no PoE", "IR 30 m"] },
  },
  "reolink-rlc-520a": {
    vendor: "reolink",
    name: "Reolink RLC-520A",
    img: "https://home-cdn.reolink.us/wp-content/uploads/2025/07/090349121752032952.7475.jpg.webp",
    amazon: "https://www.amazon.de/dp/B08KG1517Y",
    url: "https://reolink.com/product/rlc-520a/",
    price: 55,
    res: '5 MP · 1/2.7"',
    ir: 30,
    fov: 80,
    poe: "PoE (802.3af)",
    ip: "IP67",
    out: true,
    note: {
      de: "Günstiger PoE-Einstieg als Dome. Reicht für Nebeneingang, Garage, Werkstatt.",
      en: "Budget PoE dome. Enough for a side door, garage or workshop.",
    },
    tags: {
      de: ["5 MP", "günstig", "IR 30 m", "ONVIF"],
      en: ["5 MP", "budget", "IR 30 m", "ONVIF"],
    },
  },
  // --- Netatmo (app/cloud, no NVR; outdoor model replaces a 230V light fixture) ---
  "netatmo-outdoor": {
    vendor: "netatmo",
    name: "Netatmo Außenkamera",
    img: "https://www.netatmo.com/img/5a052ce9-ea06-451a-a644-03555c010709",
    amazon: "https://www.amazon.de/dp/B0B8DWD24V",
    url: "https://www.netatmo.com/de-de/outdoor-camera-original-black",
    price: 250,
    res: "2K+ HDR",
    ir: 15,
    fov: 130,
    poe: "kein PoE · 230 V (ersetzt eine Außenleuchte)",
    ip: "IP66",
    out: true,
    wifi: true,
    note: {
      de: "Kamera, Flutlicht und Sirene in einer Außenleuchte. Speichert lokal ohne Abo, braucht WLAN und 230 V. Kein NVR — nur App.",
      en: "Camera, floodlight and siren in an outdoor light. Local storage, no subscription, needs Wi-Fi and mains. No NVR — app only.",
    },
    tags: {
      de: ["WLAN", "kein PoE", "Strom nötig", "Flutlicht", "kein NVR"],
      en: ["Wi-Fi", "no PoE", "needs power", "floodlight", "no NVR"],
    },
  },
  "netatmo-indoor": {
    vendor: "netatmo",
    name: "Netatmo Innenkamera",
    img: "https://www.netatmo.com/img/d4bbd85e-7be3-41bf-96ef-5a5828c84f75",
    amazon: "https://www.amazon.de/dp/B0DVLQHLJB",
    url: "https://www.netatmo.com/de-de/indoor-camera-advance-black",
    price: 250,
    res: "2K HDR",
    ir: 0,
    fov: 130,
    poe: "kein PoE · USB-Netzteil",
    ip: "",
    out: false,
    wifi: true,
    note: {
      de: "Innen: Gesichtserkennung, mechanische Blende, lokale Speicherung ohne Abo. Kein NVR — nur App.",
      en: "Indoor: face recognition, mechanical shutter, local storage without subscription. No NVR — app only.",
    },
    tags: {
      de: ["innen", "WLAN", "kein PoE", "kein NVR"],
      en: ["indoor", "Wi-Fi", "no PoE", "no NVR"],
    },
  },
};

export const APS: Record<string, Ap> = {
  "u7-lite": {
    name: "U7 Lite",
    img: "https://cdn.ecomm.ui.com/products/253cc208-4b09-4b2e-9d1a-7aa1e8f93507/49241c96-878f-4e40-8541-c2e89c1c5e6e.png",
    amazon: "https://www.amazon.de/dp/B0F2GCYRGS",
    url: "wifi-entry/products/u7-lite",
    price: 99,
    radius: 14,
    out: false,
    wifi: "WiFi 7 · 2×2",
    poe: "PoE (802.3af)",
    ip: "IP20",
    note: {
      de: "WiFi 7, 2×2, innen. Reicht für ein kleines Haus oder den Stall innen.",
      en: "Wi-Fi 7, 2×2, indoor. Enough for a small house or inside the stable.",
    },
  },
  "u7-pro": {
    name: "U7 Pro",
    img: "https://cdn.ecomm.ui.com/products/fa8dd4e4-36c8-4c79-a928-22c7bff2ce29/ab5bc8a4-6135-402e-a695-e3ea5e16d3e6.png",
    amazon: "https://www.amazon.de/dp/B0CSR63FMH",
    url: "wifi-flagship/products/u7-pro",
    price: 189,
    radius: 18,
    out: false,
    wifi: "WiFi 7 · 6 GHz",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "WiFi 7, 6 GHz, innen. Der Standard-AP fürs Wohnhaus.",
      en: "Wi-Fi 7, 6 GHz, indoor. The default AP for the house.",
    },
  },
  "u7-outdoor": {
    name: "U7 Outdoor",
    img: "https://cdn.ecomm.ui.com/products/62cc30b7-9559-480f-9668-b9edf40c0772/f2010c22-ff34-48e5-81f4-e7dad275d3c0.png",
    amazon: "https://www.amazon.de/dp/B0DGBHNMSL",
    url: "wifi-outdoor/products/u7-outdoor",
    price: 199,
    radius: 35,
    out: true,
    wifi: "WiFi 7 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP67",
    note: {
      de: "WiFi 7, IP67, Wandmontage außen. Hof, Wiese, Stallvorplatz.",
      en: "Wi-Fi 7, IP67, outdoor wall mount. Yard, paddock, stable forecourt.",
    },
  },
  "u7-pro-outdoor": {
    name: "U7 Pro Outdoor",
    img: "https://cdn.ecomm.ui.com/products/5b68693b-679c-4a17-867a-bf9fab51dc23/d5bec576-cbd7-4de2-a688-e4323147afcb.png",
    amazon: "https://www.amazon.de/dp/B0F9JT2GQ2",
    url: "wifi-outdoor/products/u7-pro-outdoor",
    price: 250,
    radius: 45,
    out: true,
    wifi: "WiFi 7 · 6 GHz",
    poe: "PoE+ (802.3at)",
    ip: "IP67",
    note: {
      de: "WiFi 7, IP67, Richtantenne. Wenn eine Seite gezielt weit abgedeckt werden soll.",
      en: "Wi-Fi 7, IP67, directional. When one side needs to be covered far and on purpose.",
    },
  },
  // --- more UniFi, TP-Link Omada, MikroTik ---
  "u6-plus": {
    vendor: "ubiquiti",
    name: "U6+",
    img: "https://cdn.ecomm.ui.com/products/6d5c6141-e2e9-416a-b789-53e59416bb1a/853bc73b-f65b-4e59-a171-75c9a4a4615e.png",
    amazon: "https://www.amazon.de/dp/B0BYL7G7SZ",
    url: "all-wifi/products/u6-plus",
    price: 89,
    radius: 15,
    out: false,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE (802.3af)",
    ip: "IP20",
    note: {
      de: "WiFi 6, günstig, innen. Wohnräume oder kleine Nebenräume.",
      en: "Wi-Fi 6, cheap, indoor. Living areas or small side rooms.",
    },
  },
  "u6-enterprise": {
    vendor: "ubiquiti",
    name: "U6 Enterprise",
    img: "https://cdn.ecomm.ui.com/products/f9118c0f-060b-4fd7-99ce-ace671c7a1fe/6f2a87a4-193d-43e0-b253-aa0ea0795694.png",
    amazon: "https://www.amazon.de/dp/B0B395SS6T",
    url: "wifi-flagship/products/u6-enterprise",
    price: 250,
    radius: 20,
    out: false,
    wifi: "WiFi 6E · 4×4 · 6 GHz",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "WiFi 6E mit 6 GHz, 4×4, innen. Für viele Geräte im Haupthaus.",
      en: "Wi-Fi 6E with 6 GHz, 4×4, indoor. Many clients in the main house.",
    },
  },
  "u6-iw": {
    vendor: "ubiquiti",
    name: "U6 In-Wall",
    img: "https://cdn.ecomm.ui.com/products/9e487835-2aa9-4813-b210-732744a2884a/cac2e05e-2e46-4d47-84b2-7e3bb7d7ca1a.png",
    amazon: "https://www.amazon.de/dp/B09TYD6HX1",
    url: "wifi-wall/products/u6-iw",
    price: 160,
    radius: 12,
    out: false,
    wifi: "WiFi 6 · 4×4",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "Unterputz in der Netzwerkdose, mit 4-Port-Switch. Ein Zimmer.",
      en: "In-wall in the network outlet, with a 4-port switch. One room.",
    },
  },
  "u7-pro-wall": {
    vendor: "ubiquiti",
    name: "U7 Pro Wall",
    img: "https://cdn.ecomm.ui.com/products/7dacb4f6-b703-4154-9264-784f2eb0dbda/f1cb65a5-c557-4e02-bcbb-090502a95b84.png",
    amazon: "https://www.amazon.de/dp/B0FCYNZ7PR",
    url: "all-wifi/products/u7-pro-wall",
    price: 185,
    radius: 15,
    out: false,
    wifi: "WiFi 7 · 2×2 · 6 GHz",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "WiFi 7 an der Wand statt Decke, 2,5 GbE. Einzelne Räume.",
      en: "Wi-Fi 7 on the wall instead of the ceiling, 2.5 GbE. Single rooms.",
    },
  },
  "omada-eap610": {
    vendor: "tplink",
    name: "TP-Link EAP610",
    img: "https://static.tp-link.com/upload/image-line/overview_01_large_20241230033757v.jpg",
    amazon: "https://www.amazon.de/dp/B09XM74VQL",
    url: "https://www.omadanetworks.com/de/business-networking/omada-wifi-ceiling-mount/eap610/",
    price: 83,
    radius: 15,
    out: false,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "Günstiger Decken-AP innen, WiFi 6. Omada-Controller oder Standalone.",
      en: "Cheap indoor ceiling AP, Wi-Fi 6. Omada controller or standalone.",
    },
  },
  "omada-eap773": {
    vendor: "tplink",
    name: "TP-Link EAP773",
    img: "https://static.tp-link.com/upload/image-line/3_large_20230808055953d.jpg",
    amazon: "https://www.amazon.de/dp/B0CMBZQXFH",
    url: "https://www.omadanetworks.com/de/business-networking/omada-wifi-ceiling-mount/eap773/",
    price: 189,
    radius: 20,
    out: false,
    wifi: "WiFi 7 · 2×2 · 6 GHz",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "WiFi 7 Tri-Band mit 10-GbE-Port, innen. Das Omada-Flaggschiff fürs Haus.",
      en: "Wi-Fi 7 tri-band with a 10 GbE port, indoor. Omada's flagship for the house.",
    },
  },
  "omada-eap650-outdoor": {
    vendor: "tplink",
    name: "TP-Link EAP650-Outdoor",
    img: "https://static.tp-link.com/upload/image-line/EAP650-Outdoor_UN_1.0_01_large_20250109102731z.jpg",
    amazon: "https://www.amazon.de/dp/B0C5JRZQ96",
    url: "https://www.omadanetworks.com/de/business-networking/omada-wifi-outdoor/eap650-outdoor/",
    price: 159,
    radius: 40,
    out: true,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP67",
    note: {
      de: "WiFi 6, IP67, Wandmontage außen. Hof, Garten, Nebengebäude.",
      en: "Wi-Fi 6, IP67, outdoor wall mount. Yard, garden, outbuildings.",
    },
  },
  "omada-eap625-outdoor-hd": {
    vendor: "tplink",
    name: "TP-Link EAP625-Outdoor HD",
    img: "https://static.tp-link.com/upload/image-line/overview_01_large_20241227055620p.jpg",
    amazon: "https://www.amazon.de/dp/B0CSSSBHK9",
    url: "https://www.omadanetworks.com/de/business-networking/omada-wifi-outdoor/eap625-outdoor-hd/",
    price: 166,
    radius: 30,
    out: true,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP68",
    note: {
      de: "Vergossen, IP68, viele Nutzer. Für harte Umgebung außen.",
      en: "Fully potted, IP68, many users. For harsh outdoor spots.",
    },
  },
  "mikrotik-cap-ax": {
    vendor: "mikrotik",
    name: "MikroTik cAP ax",
    img: "https://cdn.mikrotik.com/web-assets/rb_images/2247_lg.webp",
    amazon: "https://www.amazon.de/dp/B0C2K94R5D",
    url: "https://mikrotik.com/product/cap_ax",
    price: 105,
    radius: 15,
    out: false,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP20",
    note: {
      de: "Decken-AP mit PoE-Durchschleife für ein zweites Gerät. RouterOS.",
      en: "Ceiling AP with PoE pass-through for a second device. RouterOS.",
    },
  },
  "mikrotik-wap-ax": {
    vendor: "mikrotik",
    name: "MikroTik wAP ax",
    img: "https://cdn.mikrotik.com/web-assets/rb_images/2410_lg.webp",
    amazon: "https://www.amazon.de/dp/B0DT4PJ62N",
    url: "https://mikrotik.com/product/wap_ax",
    price: 75,
    radius: 35,
    out: true,
    wifi: "WiFi 6 · 2×2",
    poe: "PoE+ (802.3at)",
    ip: "IP54",
    note: {
      de: "Sehr günstig, wetterfest (IP54), außen. Hof oder Nebengebäude.",
      en: "Very cheap, weatherproof (IP54), outdoor. Yard or outbuildings.",
    },
  },
  // --- AVM FRITZ!Repeater as wired APs (mains socket instead of PoE) ---
  "fritz-repeater-1200-ax": {
    vendor: "avm",
    name: "FRITZ!Repeater 1200 AX",
    img: "https://fritz.com/cdn/shop/files/fritzrepeater_1200_ax_2000x2000px.webp",
    amazon: "https://www.amazon.de/dp/B09N4X3DTJ",
    url: "https://fritz.com/en/products/fritz-repeater-1200-ax-20002974",
    price: 83,
    radius: 12,
    out: false,
    wifi: "WiFi 6 · 2×2",
    poe: "kein PoE · Steckdose",
    ip: "IP20",
    note: {
      de: "Steckdosen-Repeater, per LAN als AP nutzbar. Ein Zimmer, im Mesh mit der FRITZ!Box.",
      en: "Plug-in repeater, usable as an AP over LAN. One room, in mesh with the FRITZ!Box.",
    },
    tags: { de: ["kein PoE", "Steckdose", "innen"], en: ["no PoE", "mains socket", "indoor"] },
  },
  "fritz-repeater-3000-ax": {
    vendor: "avm",
    name: "FRITZ!Repeater 3000 AX",
    img: "https://fritz.com/cdn/shop/files/fritzrepeater_3000_ax_2000x2000px.webp",
    amazon: "https://www.amazon.de/dp/B0BKGZZP2P",
    url: "https://fritz.com/en/products/fritz-repeater-3000-ax-20003197",
    price: 180,
    radius: 18,
    out: false,
    wifi: "WiFi 6 · 2×2 · Tri-Band",
    poe: "kein PoE · Steckdose",
    ip: "IP20",
    note: {
      de: "Drei Funkeinheiten, 2× LAN. Per Kabel an die FRITZ!Box, Raum mit mehr Geräten.",
      en: "Three radios, 2× LAN. Wired to the FRITZ!Box, a room with more devices.",
    },
    tags: { de: ["kein PoE", "Steckdose", "innen"], en: ["no PoE", "mains socket", "indoor"] },
  },
  "fritz-repeater-6000": {
    vendor: "avm",
    name: "FRITZ!Repeater 6000",
    img: "https://fritz.com/cdn/shop/files/fritzrepeater_6000_2000x2000px.webp",
    amazon: "https://www.amazon.de/dp/B092VWMBZ2",
    url: "https://fritz.com/en/products/fritz-repeater-6000",
    price: 220,
    radius: 22,
    out: false,
    wifi: "WiFi 6 · 4×4 · Tri-Band",
    poe: "kein PoE · Steckdose",
    ip: "IP20",
    note: {
      de: "AVMs stärkster WiFi-6-Repeater, 2,5-GbE-Port. Als AP per Kabel in Werkstatt oder großem Raum.",
      en: "AVM's strongest Wi-Fi 6 repeater, 2.5 GbE port. As a wired AP in a workshop or large room.",
    },
    tags: { de: ["kein PoE", "Steckdose", "innen"], en: ["no PoE", "mains socket", "indoor"] },
  },
};

// Junctions: multiple conduits meet here. Conduit ends snap onto them
// and move along until someone deliberately drags the end away.
export const JUNCTIONS: Record<string, Junction> = {
  shaft: {
    kind: "housing",
    vendor: "any",
    name: { de: "Kabelschacht DN 300", en: "Cable shaft DN 300" },
    price: 40,
    ip: "IP54",
    ports: 6,
    power: false,
    dig: true,
    img: "https://www.kabelschacht24.de/storage/images/image?remote=https%3A%2F%2Fwww.kabelschacht24.de%2FWebRoot%2FStore16%2FShops%2F61464916%2F4790%2F70A5%2F3434%2F447B%2FEACD%2FC0A8%2F28BA%2FD775%2FPPK30.jpg&shop=61464916",
    amazon: "https://www.amazon.de/dp/B0FP2GYZ8T",
    amazonSimilar: true,
    url: "https://www.kabelschacht24.de/p/e-trick-pp-kunststoffkabelschacht-k30-300x300x300-begehbare-abdeckung",
    use: { de: "Rohre treffen sich, Kabel laufen durch", en: "conduits meet, cables run through" },
    tags: {
      de: ["Erdarbeit", "kein Strom", "später zugänglich"],
      en: ["earthwork", "no power", "reachable later"],
    },
    mount: { de: "Erdeinbau, Deckel begehbar", en: "Buried, walk-on lid" },
    note: {
      de: "Der Standard am Abzweig: Rohre enden im Schacht, Kabel laufen durch, nichts wird gespleißt. Nachträglich zugänglich.",
      en: "The default at a branch point: conduits end in the shaft, cables run through, nothing is spliced. Reachable later.",
    },
  },
  "shaft-s": {
    kind: "housing",
    vendor: "any",
    name: { de: "Kabelschacht DN 200 (klein)", en: "Cable shaft DN 200 (small)" },
    price: 37,
    ip: "IP54",
    ports: 4,
    power: false,
    dig: true,
    img: "https://www.kabelschacht24.de/storage/images/image?remote=https%3A%2F%2Fwww.kabelschacht24.de%2FWebRoot%2FStore16%2FShops%2F61464916%2F4873%2F6E86%2F68EA%2F50ED%2F3AB8%2FC0A8%2F28BA%2FEF84%2FPPK30.jpg&shop=61464916",
    url: "https://www.kabelschacht24.de/p/e-trick-pp-k20-kabelschacht-aus-kunststoff-begehbare-abdeckung",
    use: {
      de: "kleiner Abzweig für zwei, drei dünne Rohre",
      en: "small branch for two or three thin conduits",
    },
    tags: {
      de: ["Erdarbeit", "kein Strom", "später zugänglich"],
      en: ["earthwork", "no power", "reachable later"],
    },
    mount: { de: "Erdeinbau, Deckel begehbar", en: "Buried, walk-on lid" },
    note: {
      de: "Kleinere Ausführung des Standardschachts, 200×200×200 mm: reicht für einen Abzweig mit zwei, drei dünnen Rohren. Ab vier Kanälen wird es eng, dann der große Schacht.",
      en: "Smaller version of the standard shaft, 200×200×200 mm: enough for a branch with two or three thin conduits. Gets tight from four channels on, then take the larger shaft.",
    },
  },
  pit: {
    kind: "housing",
    vendor: "any",
    name: { de: "Kabelschacht befahrbar, Kl. B125", en: "Drivable cable pit, class B125" },
    price: 379,
    ip: "IP54",
    ports: 4,
    power: false,
    dig: true,
    img: "https://www.kabelschacht24.de/storage/images/image?remote=https%3A%2F%2Fwww.kabelschacht24.de%2FWebRoot%2FStore16%2FShops%2F61464916%2F61FA%2F9D14%2F334C%2F5A5A%2F08F6%2F0A0C%2F6D13%2F5628%2FQuattro.jpg&shop=61464916",
    url: "https://www.kabelschacht24.de/en/p/e-trick-quattro-kunststoffkabelschacht-290x270mm-mit-boden",
    use: {
      de: "Abzweig unter einer Zufahrt oder Toreinfahrt",
      en: "branch under a driveway or gate crossing",
    },
    tags: {
      de: ["Erdarbeit", "kein Strom", "befahrbar bis 12,5 t"],
      en: ["earthwork", "no power", "drivable up to 12.5 t"],
    },
    mount: { de: "Erdeinbau unter befestigter Fläche", en: "Buried under a paved surface" },
    note: {
      de: "Faserverbundkunststoff statt PP, Deckel Klasse B125 (12,5 t): der einzige Schacht hier, der unter einer Autoeinfahrt liegen darf. Im Rasen wäre er zehnmal so teuer wie nötig.",
      en: "Fibre-composite plastic instead of PP, lid class B125 (12.5 t): the only shaft here allowed under a car driveway. In a lawn it costs ten times what is needed.",
    },
  },
  box: {
    kind: "housing",
    vendor: "any",
    name: { de: "Gel-Abzweigdose IP68", en: "Gel-filled junction box IP68" },
    price: 15,
    ip: "IP68",
    ports: 3,
    power: false,
    dig: true,
    img: "https://www.elektrikshop.de/images/product_images/original_images/5165_0.jpg",
    amazon: "https://www.amazon.de/dp/B00M1UXU3Q",
    amazonSimilar: true,
    url: "https://www.elektrikshop.de/cellpack-gel-muffe-easycell-easy-2-v-3x1-5-2-5.html",
    use: {
      de: "billigster Abzweig, danach zugeschüttet",
      en: "cheapest branch, buried afterwards",
    },
    tags: {
      de: ["Erdarbeit", "kein Strom", "nicht mehr zugänglich"],
      en: ["earthwork", "no power", "not reachable"],
    },
    mount: { de: "Direkt im Erdreich", en: "Direct burial" },
    note: {
      de: "Billig und dicht, aber einmalig: zum Öffnen muss aufgegraben werden. Nur für Abzweige, die sich nie ändern.",
      en: "Cheap and watertight, but one-shot: opening it means digging. Only for branches that never change.",
    },
  },
  cab: {
    kind: "housing",
    vendor: "any",
    name: { de: "Verteilerkasten außen", en: "Outdoor distribution cabinet" },
    price: 120,
    ip: "IP65",
    ports: 8,
    power: false,
    dig: false,
    img: "https://www.elektroland24.de/media/f9/3a/0f/1671001746/66f6242119e48d8cbd0fb78d1bf56cbca37b7a6a.jpg",
    amazon: "https://www.amazon.de/dp/B011OCUFWA",
    url: "https://www.elektroland24.de/elektroinstallation/verteilerschraenke/verteilerkasten-aufputz/sicherungskasten-spelsberg/spelsberg-aki-12-kleinverteiler-ip65-12te-witterungsbestaendig.html",
    use: {
      de: "Abzweig über Grund, mit Platz für Technik",
      en: "branch above ground, with room for gear",
    },
    tags: {
      de: ["keine Erdarbeit", "kein Strom", "Platz für Switch"],
      en: ["no earthwork", "no power", "room for a switch"],
    },
    mount: { de: "Wand- oder Sockelmontage", en: "Wall or pedestal mount" },
    note: {
      de: "Über Grund, mit Platz für Patchfeld, Switch oder Überspannungsschutz. Wenn am Abzweig auch Technik sitzen soll.",
      en: "Above ground, with room for a patch panel, switch or surge protection. For when the branch point also holds equipment.",
    },
  },
  "cab-l": {
    kind: "housing",
    vendor: "any",
    name: {
      de: "Verteilerkasten außen, groß (2-reihig)",
      en: "Outdoor distribution cabinet, large (2-row)",
    },
    price: 119,
    ip: "IP65",
    ports: 12,
    power: false,
    dig: false,
    img: "https://www.elektrikshop.de/images/product_images/popup_images/498_0.jpg",
    url: "https://www.elektrikshop.de/kleinverteiler-2-reihig-feuchtraum-ip65-73342801-ak28-spelsberg.html",
    use: {
      de: "Abzweig über Grund mit Platz für mehrere Geräte",
      en: "branch above ground with room for several devices",
    },
    tags: {
      de: ["keine Erdarbeit", "kein Strom", "DIN-Schiene", "viel Platz"],
      en: ["no earthwork", "no power", "DIN rail", "plenty of room"],
    },
    mount: { de: "Wand- oder Sockelmontage", en: "Wall or pedestal mount" },
    note: {
      de: "Zweireihige Ausführung des Verteilerkastens: Switch, Überspannungsschutz und PoE-Injektor passen nebeneinander auf die DIN-Schiene. Für einen Durchgangs-Abzweig reicht der kleine.",
      en: "Two-row version of the distribution cabinet: switch, surge protector and PoE injector fit side by side on the DIN rail. A pass-through branch is fine with the small one.",
    },
  },
  "cab-sw": {
    kind: "housing",
    vendor: "any",
    name: {
      de: "Leergehäuse IP66 für Switch, klein",
      en: "Empty enclosure IP66 for a switch, small",
    },
    price: 25,
    ip: "IP66",
    ports: 2,
    power: false,
    dig: false,
    img: "https://www.elektrotresen.de/media/images/info/307/141/8403140/10840314099.jpg",
    url: "https://www.elektrotresen.de/Installationsmaterial/Abzweig-und-Befestigungsmaterial/Kabelabzweigkaesten/Leergehaeuse/Spelsberg-Leergeh-use-TG-ABS-2012-8-o.html",
    use: {
      de: "ein kleiner Switch draußen an Wand oder Mast",
      en: "a small switch outdoors on a wall or pole",
    },
    tags: {
      de: ["keine Erdarbeit", "kein Strom", "nur kleine Geräte"],
      en: ["no earthwork", "no power", "small devices only"],
    },
    mount: { de: "Wand- oder Mastmontage", en: "Wall or pole mount" },
    note: {
      de: "Leeres ABS-Gehäuse, 202×122×75 mm: Platz für einen 5-Port-Switch mit Kabelverschraubungen, nicht für acht Ports. Dafür der große Verteilerkasten.",
      en: "Empty ABS enclosure, 202×122×75 mm: room for a 5-port switch with cable glands, not for eight ports. Use the large cabinet for those.",
    },
  },
  // Not a housing but a location: the gear sits inside the building. Costs nothing,
  // but carries the same devices as a distribution cabinet.
  indoor: {
    kind: "housing",
    vendor: "any",
    name: { de: "Innen, Wand oder Regal", en: "Indoors, wall or shelf" },
    price: 0,
    ip: "IP20",
    ports: 0,
    power: false,
    dig: false,
    use: {
      de: "Technik im Gebäude, kein Gehäuse nötig",
      en: "gear inside the building, no housing needed",
    },
    tags: {
      de: ["keine Erdarbeit", "trocken", "jederzeit zugänglich"],
      en: ["no earthwork", "dry", "reachable any time"],
    },
    mount: { de: "Wand, Regal oder Netzwerkschrank", en: "Wall, shelf or network rack" },
    note: {
      de: "Kein Gehäuse — das Gerät sitzt im Gebäude, an der Wand oder im Netzwerkschrank.",
      en: "No housing — the device sits inside the building, on a wall or in the network rack.",
    },
  },
  rack19: {
    kind: "housing",
    vendor: "digitus",
    name: {
      de: "DIGITUS DN-19 09-U-EC-SW (Wandgehäuse 19″, 9 HE)",
      en: "DIGITUS DN-19 09-U-EC-SW (19-inch wall rack, 9U)",
    },
    price: 125,
    ip: "IP20",
    ports: 9,
    power: false,
    dig: false,
    img: "https://cdn-reichelt.de/bilder/web/artikel_ws/E910%2FDIGITUS_DN-19_09-U-EC-SW_001.jpg?type=Product&",
    url: "https://www.reichelt.com/de/en/shop/product/19_wall-mounted_housing_9u_450mm_depth_black-370703",
    use: {
      de: "Switch, Patchfeld und Router zusammen im Haus",
      en: "switch, patch panel and router together in the house",
    },
    tags: {
      de: ["keine Erdarbeit", "trocken", "abschließbar"],
      en: ["no earthwork", "dry", "lockable"],
    },
    mount: { de: "Wandmontage, Glastür", en: "Wall mount, glass door" },
    note: {
      de: "Neun Höheneinheiten für Switch, Patchfeld und Router, abschließbar. Für die Zentrale im Haus; ein einzelnes Gerät hängt genauso gut an einem Brett.",
      en: "Nine rack units for switch, patch panel and router, lockable. For the hub inside the house; a single device does just as well on a plain shelf.",
    },
  },
  // Fibre is normally not split at a junction — it runs through uncut
  // Only when it really has to be separated does it need a splice box.
  splice: {
    kind: "device",
    vendor: "any",
    name: { de: "Spleißbox IP68 (LWL)", en: "Splice box IP68 (fibre)" },
    price: 180,
    ip: "IP68",
    ports: 2,
    power: false,
    powerIn: "none",
    dig: true,
    img: "https://cdn-reichelt.de/bilder/web/artikel_ws/E910%2FDIGITUS_DN-941091_01.jpg?type=Product&",
    amazon: "https://www.amazon.de/dp/B0C4TN3NGX",
    url: "https://www.reichelt.com/de/en/shop/product/fiber_optic_splice_closure_48_cores_dome-shaped-394676",
    use: {
      de: "nur wenn eine Faser wirklich getrennt wird",
      en: "only when a fibre really gets cut",
    },
    tags: {
      de: ["Erdarbeit", "kein Strom", "Fachbetrieb"],
      en: ["earthwork", "no power", "needs a specialist"],
    },
    mount: { de: "im Schacht, Erdeinbau", en: "inside the shaft, buried" },
    note: {
      de: "Nur nötig, wenn eine Faser wirklich getrennt werden muss. Der Normalfall am Abzweig ist Durchziehen — zwei Ziele heißt zwei Kabel im Stammrohr, nicht ein geteiltes.",
      en: "Only needed when a fibre really has to be cut. The normal case at a branch is pulling through — two destinations mean two cables in the trunk conduit, not one split one.",
    },
  },
  // At the fibre end, light has to become copper again. This is the piece
  // that was missing from the map so far.
  flex: {
    kind: "device",
    name: { de: "USW Flex 2.5G PoE (Switch)", en: "USW Flex 2.5G PoE (switch)" },
    price: 179,
    ip: "IP20",
    ports: 8,
    sfpPorts: 1,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 196,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/e9d97121-f363-4261-83db-5f74e093a304/dd55113e-93b2-40da-b10b-945ab4d609d0.png",
    amazon: "https://www.amazon.de/dp/B0DV6CDXKT",
    url: "switching-utility-poe/products/usw-flex-2-5g-8-poe",
    use: {
      de: "Glasfaser rein, 8× Netzwerk mit PoE raus",
      en: "fibre in, 8× network with PoE out",
    },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "PoE++", "trocken montieren"],
      en: ["needs power", "fibre → LAN", "PoE++", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Hier wird aus Glasfaser wieder Kupfer: SFP+ rein, 8× PoE++ (196 W) raus. Ein Switch je Gebäude, Kameras und APs hängen daran. Braucht Strom.",
      en: "This is where fibre turns back into copper: SFP+ in, 8× PoE++ (196 W) out. One switch per building, cameras and APs hang off it. Needs power.",
    },
  },
  lite8: {
    kind: "device",
    name: { de: "USW Lite 8 PoE (Switch)", en: "USW Lite 8 PoE (switch)" },
    price: 99,
    ip: "IP20",
    ports: 8,
    sfpPorts: 0,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 52,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/75c44878-4e73-446e-8e86-f207db6b2b7c/53b8b06b-69c7-424f-bb81-2f8405356c65.png",
    amazon: "https://www.amazon.de/dp/B08MBRKG2Q",
    url: "switching-utility-poe/products/usw-lite-8-poe",
    use: {
      de: "8× Netzwerk mit PoE, aber nur über Cat6A",
      en: "8× network with PoE, but fed by Cat6A",
    },
    tags: { de: ["Strom nötig", "keine Glasfaser", "PoE"], en: ["needs power", "no fibre", "PoE"] },
    mount: { de: "innen", en: "indoors" },
    note: {
      de: "Günstiger, aber ohne SFP: die Zuleitung muss dann Cat6A sein, keine Glasfaser. 52 W PoE-Budget.",
      en: "Cheaper, but no SFP: the feed then has to be Cat6A, not fibre. 52 W PoE budget.",
    },
  },
  conv: {
    kind: "device",
    name: { de: "Medienkonverter SM → RJ45", en: "Media converter SM → RJ45" },
    price: 60,
    ip: "IP20",
    ports: 1,
    sfpPorts: 1,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://cdn-reichelt.de/bilder/web/artikel_ws/E910%2FDIGITUS_DN-82130_001.jpg?type=Product&",
    amazon: "https://www.amazon.de/dp/B005F0HMHY",
    url: "https://www.reichelt.com/de/en/shop/product/media_converter_gigabit_ethernet_rj45_sfp-370781",
    use: {
      de: "Glasfaser rein, genau ein Netzwerkport raus",
      en: "fibre in, exactly one network port out",
    },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "nur 1 Gerät"],
      en: ["needs power", "fibre → LAN", "1 device only"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Für ein einzelnes Gerät am Glasfaserende — eine Kamera, ein AP. Billiger als ein Switch, aber nur ein Port und PoE muss extra kommen.",
      en: "For a single device at the end of a fibre — one camera, one AP. Cheaper than a switch, but only one port and PoE has to come separately.",
    },
  },
  // --- more switches and converters: UniFi, TP-Link Omada, MikroTik ---
  "usw-ultra-60w": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "USW Ultra 60W (Switch)", en: "USW Ultra 60W (switch)" },
    price: 129,
    ip: "IP20",
    ports: 8,
    sfpPorts: 0,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 52,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/d1af5d9b-b74c-4881-99af-033b71ed1590/f80567f8-ba09-4a75-982d-6fd636623492.png",
    amazon: "https://www.amazon.de/dp/B0D1XRYF2G",
    url: "switching-utility/collections/pro-ultra/products/usw-ultra-60w",
    use: { de: "8× PoE+, kompakt, lüfterlos", en: "8× PoE+, compact, fanless" },
    tags: {
      de: ["Strom nötig", "kein SFP · Medienkonverter davor", "PoE+ 52 W", "trocken montieren"],
      en: ["needs power", "no SFP · media converter first", "PoE+ 52 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Kleiner 8-Port-PoE+-Switch (52 W), lüfterlos, kein SFP: die Faser endet davor in einem Medienkonverter.",
      en: "Small 8-port PoE+ switch (52 W), fanless, no SFP: the fibre ends in a media converter before it.",
    },
  },
  "usw-lite-16-poe": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "USW Lite 16 PoE (Switch)", en: "USW Lite 16 PoE (switch)" },
    price: 179,
    ip: "IP20",
    ports: 16,
    sfpPorts: 0,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 45,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/e726eace-a772-4f12-bfad-c68baf20e51f/9ecfc657-5e31-4135-89b5-46b3537b35fc.png",
    amazon: "https://www.amazon.de/dp/B08KC1YQZ9",
    url: "switching-utility/products/usw-lite-16-poe",
    use: { de: "16 Ports, 8× PoE+", en: "16 ports, 8× PoE+" },
    tags: {
      de: ["Strom nötig", "kein SFP · Medienkonverter davor", "PoE+ 45 W", "trocken montieren"],
      en: ["needs power", "no SFP · media converter first", "PoE+ 45 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "16 Ports, davon 8 mit PoE+ (45 W gesamt), kein SFP. Für den Verteiler mit vielen Kabeln, Faser über Medienkonverter.",
      en: "16 ports, 8 of them PoE+ (45 W total), no SFP. For a distributor with many cables, fibre via media converter.",
    },
  },
  "usw-industrial": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "USW Industrial (Switch)", en: "USW Industrial (switch)" },
    price: 449,
    ip: "IP20",
    ports: 10,
    sfpPorts: 0,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 430,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/e9c1cd60-bc9d-4e80-9e17-7a3dbecf9f29/2fad00b0-046a-4040-abb5-a206120bffb6.png",
    amazon: "https://www.amazon.de/dp/B081QW97LB",
    url: "switching-utility/products/usw-industrial",
    use: { de: "8× PoE++, robust, lüfterlos", en: "8× PoE++, rugged, fanless" },
    tags: {
      de: ["Strom nötig", "kein SFP · Medienkonverter davor", "PoE++ 430 W", "trocken montieren"],
      en: ["needs power", "no SFP · media converter first", "PoE++ 430 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Aluminiumgehäuse, lüfterlos, 10 Gigabit-Ports, davon 8× PoE++ (60 W je Port). Für Staub, Hitze, Kälte. Kein SFP.",
      en: "Aluminium housing, fanless, 10 gigabit ports, 8 of them PoE++ (60 W per port). For dust, heat, cold. No SFP.",
    },
  },
  "omada-sg2008p": {
    kind: "device",
    vendor: "tplink",
    name: { de: "TP-Link SG2008P (Switch)", en: "TP-Link SG2008P (switch)" },
    price: 86,
    ip: "IP20",
    ports: 8,
    sfpPorts: 0,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 62,
    dig: false,
    img: "https://static.tp-link.com/TL-SG2008P(UN)1.0_01_normal_1594869482015x.jpg",
    amazon: "https://www.amazon.de/dp/B08GDBVJXH",
    url: "https://www.tp-link.com/de/business-networking/omada-sdn-switch/sg2008p/",
    use: { de: "8 Ports, 4× PoE+, günstig", en: "8 ports, 4× PoE+, cheap" },
    tags: {
      de: ["Strom nötig", "kein SFP · Medienkonverter davor", "PoE+ 62 W", "trocken montieren"],
      en: ["needs power", "no SFP · media converter first", "PoE+ 62 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "8 Ports, 4× PoE+ (62 W), kein SFP. Günstigster Omada-Einstieg; Faser über MC220L.",
      en: "8 ports, 4× PoE+ (62 W), no SFP. Cheapest Omada entry; fibre via MC220L.",
    },
  },
  "omada-sg2210mp": {
    kind: "device",
    vendor: "tplink",
    name: { de: "TP-Link TL-SG2210MP (Switch)", en: "TP-Link TL-SG2210MP (switch)" },
    price: 150,
    ip: "IP20",
    ports: 8,
    sfpPorts: 2,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 150,
    dig: false,
    img: "https://static.tp-link.com/TL-SG2210MP(UN)1.0-01_normal_1594869369356n.jpg",
    amazon: "https://www.amazon.de/dp/B08FRMHX14",
    url: "https://www.omadanetworks.com/de/business-networking/omada-switch-access/tl-sg2210mp/",
    use: { de: "8× PoE+ (150 W) + 2× SFP", en: "8× PoE+ (150 W) + 2× SFP" },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "PoE+ 150 W", "trocken montieren"],
      en: ["needs power", "fibre → LAN", "PoE+ 150 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "8× PoE+ mit 150 W gesamt plus 2× Gigabit-SFP: die Faser geht direkt hinein, kein Medienkonverter nötig.",
      en: "8× PoE+ with 150 W total plus 2× gigabit SFP: the fibre plugs straight in, no media converter needed.",
    },
  },
  "omada-sg3210xhp-m2": {
    kind: "device",
    vendor: "tplink",
    name: { de: "TP-Link SG3210XHP-M2 (Switch)", en: "TP-Link SG3210XHP-M2 (switch)" },
    price: 378,
    ip: "IP20",
    ports: 8,
    sfpPorts: 2,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 240,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/SG3210XHP-M2_UN_3.0_overview_01_normal_20250126032648i.jpg",
    amazon: "https://www.amazon.de/dp/B092VFS6K3",
    url: "https://www.omadanetworks.com/de/business-networking/omada-switch-access-pro/sg3210xhp-m2/",
    use: { de: "8× 2,5G PoE+ (240 W) + 2× SFP+", en: "8× 2.5G PoE+ (240 W) + 2× SFP+" },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "PoE+ 240 W", "trocken montieren"],
      en: ["needs power", "fibre → LAN", "PoE+ 240 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "8× 2,5-GbE-PoE+ mit 240 W und 2× 10G-SFP+. Für 4K-Kameras in Menge und WiFi-7-APs am Faserende.",
      en: "8× 2.5 GbE PoE+ with 240 W and 2× 10G SFP+. For lots of 4K cameras and Wi-Fi 7 APs at the fibre end.",
    },
  },
  "tplink-mc220l": {
    kind: "device",
    vendor: "tplink",
    name: { de: "TP-Link MC220L (Medienkonverter)", en: "TP-Link MC220L (media converter)" },
    price: 15,
    ip: "IP20",
    ports: 1,
    sfpPorts: 1,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/MC420L_normal_20250207082113q.jpg",
    amazon: "https://www.amazon.de/dp/B08GMCDV9P",
    url: "https://www.omadanetworks.com/de/business-networking/omada-accessory-media-converter/mc220l/",
    use: { de: "Faser → 1× Kupfer, kein PoE", en: "fibre → 1× copper, no PoE" },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "kein PoE"],
      en: ["needs power", "fibre → LAN", "no PoE"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Reiner Konverter: SFP rein, 1× Gigabit-Kupfer raus. Das billigste Faserende vor einem Switch ohne SFP.",
      en: "Plain converter: SFP in, 1× gigabit copper out. The cheapest fibre end ahead of a switch without SFP.",
    },
  },
  "mikrotik-css610": {
    kind: "device",
    vendor: "mikrotik",
    name: { de: "MikroTik CSS610-8P-2S+IN (Switch)", en: "MikroTik CSS610-8P-2S+IN (switch)" },
    price: 180,
    ip: "IP20",
    ports: 8,
    sfpPorts: 2,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 140,
    dig: false,
    img: "https://cdn.mikrotik.com/web-assets/product_files/CSS610-8P-2SIN_220840_thumb.webp",
    amazon: "https://www.amazon.de/dp/B0BC13P1Y6",
    url: "https://mikrotik.com/product/css610_8p_2s_in",
    use: { de: "8× PoE (140 W) + 2× SFP+, SwOS", en: "8× PoE (140 W) + 2× SFP+, SwOS" },
    tags: {
      de: ["Strom nötig", "Glasfaser → LAN", "PoE+ 140 W", "trocken montieren"],
      en: ["needs power", "fibre → LAN", "PoE+ 140 W", "mount dry"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "8× Gigabit-PoE-out (af/at, 140 W) plus 2× SFP+. Günstigster Weg zu echtem PoE-Budget mit direktem Faseranschluss; nur SwOS.",
      en: "8× gigabit PoE-out (af/at, 140 W) plus 2× SFP+. Cheapest route to a real PoE budget with a direct fibre uplink; SwOS only.",
    },
  },
  // --- accessories at the point: injector, extender, surge protector, SFP module ---
  // Estimated prices (no dealer price found): injector 35 €, PoE extender 39 €,
  // SFP module 20 €, CRS305 149 € (MikroTik's list price). The rest are listed.
  "usw-flex": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "USW Flex (Switch, außentauglich)", en: "USW Flex (switch, outdoor-capable)" },
    price: 89,
    ip: "IP54",
    ports: 5,
    sfpPorts: 0,
    power: true,
    powerIn: "poe",
    sfp: false,
    poe: 46,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/c9a07d37-b390-4a5b-89c5-3cdab8e011c7/4bcd3c2b-a8b1-4be1-baab-deda172291cd.png",
    url: "switching-utility/products/usw-flex",
    use: {
      de: "5 Ports mit PoE, wetterfest, ohne Kasten",
      en: "5 ports with PoE, weatherproof, no box",
    },
    tags: {
      de: ["Strom nötig", "kein SFP · Medienkonverter davor", "wetterfest", "PoE 46 W"],
      en: ["needs power", "no SFP · media converter first", "weatherproof", "PoE 46 W"],
    },
    mount: {
      de: "außen an Wand oder Mast, auch ohne Kasten",
      en: "outdoors on a wall or pole, even without a box",
    },
    note: {
      de: "Fünf Ports, davon PoE mit 46 W gesamt, wetterfest — es braucht kein zusätzliches Gehäuse. Kein SFP: die Faser endet davor in einem Medienkonverter.",
      en: "Five ports, PoE with 46 W total, weatherproof — no extra housing needed. No SFP: the fibre ends in a media converter before it.",
    },
  },
  "tplink-poe170s": {
    kind: "device",
    vendor: "tplink",
    name: { de: "TP-Link POE170S (PoE-Injektor)", en: "TP-Link POE170S (PoE injector)" },
    price: 35,
    ip: "IP20",
    ports: 2,
    sfpPorts: 0,
    poePorts: 1,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 60,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/POE170S(UN)2.20_large_20231130092227z.jpg",
    url: "https://www.tp-link.com/de/business-networking/omada-accessory-power-poe/poe170s/",
    use: {
      de: "ein einzelnes PoE-Gerät an einem Switch ohne PoE",
      en: "a single PoE device on a switch without PoE",
    },
    tags: {
      de: ["Strom nötig", "802.3af/at/bt", "60 W", "nur 1 Gerät"],
      en: ["needs power", "802.3af/at/bt", "60 W", "1 device only"],
    },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in the cabinet" },
    note: {
      de: "Speist ein einzelnes Gerät mit bis zu 60 W (802.3af/at/bt) aus einem gewöhnlichen Netzwerkport. Zwei Buchsen, aber nur eine davon geht weiter — ab zwei Geräten ist ein PoE-Switch richtig.",
      en: "Feeds a single device with up to 60 W (802.3af/at/bt) from an ordinary network port. Two sockets, but only one of them leads on — from two devices on, a PoE switch is the right answer.",
    },
  },
  "trendnet-tpe-e100": {
    kind: "device",
    vendor: "trendnet",
    name: { de: "TRENDnet TPE-E100 (PoE-Extender)", en: "TRENDnet TPE-E100 (PoE extender)" },
    price: 39,
    ip: "IP20",
    ports: 2,
    sfpPorts: 0,
    power: false,
    powerIn: "poe",
    sfp: false,
    poe: 0,
    extend: 100,
    dig: false,
    img: "https://www.trendnet.com/images/products/photos/TPE-E100_v2/TPE-E100_v2_d01_2.webp",
    url: "https://www.trendnet.com/products/PoE/PoE-Extender/TPE-E100",
    use: {
      de: "verlängert eine PoE-Strecke um bis zu 100 m",
      en: "extends a PoE run by up to 100 m",
    },
    tags: {
      de: ["Strom aus dem PoE-Budget", "802.3af/at", "100 m mehr Reichweite"],
      en: ["draws from the PoE budget", "802.3af/at", "100 m more reach"],
    },
    mount: {
      de: "in der Kabelstrecke, etwa im Verteilerkasten",
      en: "inline in the run, e.g. in the cabinet",
    },
    note: {
      de: "Sitzt mitten in der Leitung und macht aus einer 100-m-Cat-Strecke bis zu 200 m, PoE läuft mit durch. Eigenen Strom braucht er nicht, er zieht vom PoE-Budget des Switches.",
      en: "Sits mid-run and turns a 100 m Cat run into up to 200 m, PoE passing through. It needs no mains of its own, it draws from the switch's PoE budget.",
    },
  },
  "eth-sp-g2": {
    kind: "device",
    vendor: "ubiquiti",
    name: {
      de: "Ethernet-Überspannungsschutz (ETH-SP-G2)",
      en: "Ethernet surge protector (ETH-SP-G2)",
    },
    price: 12,
    ip: "IPX5",
    ports: 2,
    sfpPorts: 0,
    power: false,
    powerIn: "none",
    sfp: false,
    poe: 0,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/e46e1950-4194-4fa1-9908-5803287b52c3/62caf686-2476-4da0-be1e-e19887698024.png",
    amazon: "https://www.amazon.de/dp/B079HXKRW1",
    url: "accessories-cables/products/ethernet-surge-protector",
    use: {
      de: "Blitz- und Überspannungsschutz vor einem Außengerät",
      en: "lightning and surge protection ahead of an outdoor device",
    },
    tags: {
      de: ["kein Strom", "PoE-Durchleitung bis 60 W", "Gigabit"],
      en: ["no power draw", "PoE passthrough to 60 W", "gigabit"],
    },
    mount: { de: "in Reihe im Kabel, geerdet", en: "inline in the cable, grounded" },
    note: {
      de: "Passiv, ohne eigenen Verbrauch: leitet PoE bis 802.3bt (60 W) durch und einen Überspannungsimpuls zur Erde ab. Er ersetzt keine Erdung, er braucht eine.",
      en: "Passive, draws nothing itself: passes PoE through up to 802.3bt (60 W) and shunts a surge to earth. It does not replace grounding, it requires it.",
    },
  },
  "tplink-sm311ls": {
    kind: "device",
    vendor: "tplink",
    name: {
      de: "TP-Link SM311LS (SFP-Modul, Singlemode)",
      en: "TP-Link SM311LS (SFP module, single-mode)",
    },
    price: 20,
    ip: "IP20",
    ports: 0,
    sfpPorts: 0,
    power: false,
    powerIn: "none",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/SM311LS_UN_5.0_2310_large_20231027065237f.png",
    url: "https://www.tp-link.com/de/business-networking/omada-accessory-module-cable/sm311ls/",
    use: {
      de: "steckt in einem SFP-Schacht, verbindet über Glasfaser",
      en: "plugs into an SFP cage, links over fibre",
    },
    tags: {
      de: ["kein Strom", "immer paarweise", "20 km Singlemode"],
      en: ["no power draw", "always in pairs", "20 km single-mode"],
    },
    mount: { de: "steckt im SFP-Schacht des Switches", en: "plugs into the switch's SFP cage" },
    note: {
      de: "1000Base-LX, LC-Duplex, 20 km. Es bringt keinen eigenen Schacht mit, es belegt einen — und ohne das Gegenstück am anderen Ende bleibt die Faser dunkel.",
      en: "1000Base-LX, LC duplex, 20 km. It brings no cage of its own, it occupies one — and without its counterpart at the far end the fibre stays dark.",
    },
  },
  "mikrotik-crs305": {
    kind: "device",
    vendor: "mikrotik",
    name: { de: "MikroTik CRS305-1G-4S+IN (Switch)", en: "MikroTik CRS305-1G-4S+IN (switch)" },
    price: 149,
    ip: "IP20",
    ports: 1,
    sfpPorts: 4,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://cdn.mikrotik.com/web-assets/rb_images/1659_tm.webp",
    url: "https://mikrotik.com/product/crs305_1g_4s_in",
    use: {
      de: "vier Glasfaserstrecken an einem Punkt bündeln",
      en: "bundle four fibre runs at one point",
    },
    tags: {
      de: ["Strom nötig", "kein PoE", "4× SFP+", "nur Faseraggregation"],
      en: ["needs power", "no PoE", "4× SFP+", "fibre aggregation only"],
    },
    mount: { de: "innen, Tischgerät", en: "indoors, desktop unit" },
    note: {
      de: "Vier SFP+-Schächte (bis 10G) plus ein Gigabit-Kupferport, kein PoE. Für die Zentrale, wenn mehrere Gebäude je eine eigene Faser dorthin ziehen. Kupfergeräte dahinter brauchen einen eigenen PoE-Switch.",
      en: "Four SFP+ cages (up to 10G) plus one gigabit copper port, no PoE. For the hub when several buildings each run their own fibre there. Copper devices behind it need a PoE switch of their own.",
    },
  },
  "mikrotik-css610-8g": {
    kind: "device",
    vendor: "mikrotik",
    name: {
      de: "MikroTik CSS610-8G-2S+IN (Switch, ohne PoE)",
      en: "MikroTik CSS610-8G-2S+IN (switch, no PoE)",
    },
    price: 119,
    ip: "IP20",
    ports: 8,
    sfpPorts: 2,
    poePorts: 0,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://cdn.mikrotik.com/web-assets/rb_images/1351_tm.webp",
    url: "https://mikrotik.com/product/css610_8g_2s_in",
    use: {
      de: "zwei Fasern an einem Punkt annehmen und auf Kupfer verteilen",
      en: "take two fibres at one point and fan them out to copper",
    },
    tags: { de: ["Strom nötig", "kein PoE", "2× SFP+"], en: ["needs power", "no PoE", "2× SFP+"] },
    mount: { de: "innen oder im Verteilerkasten", en: "indoors or in a cabinet" },
    note: {
      de: "Nicht-PoE-Geschwister des CSS610-8P-2S+IN: 8× Gigabit-Kupfer plus 2× SFP+, RouterOS. Günstiger als der CRS305 (4× SFP+), wenn zwei Fasern reichen und kein PoE gebraucht wird.",
      en: "The non-PoE sibling of the CSS610-8P-2S+IN: 8× gigabit copper plus 2× SFP+, RouterOS. Cheaper than the CRS305 (4× SFP+) when two fibres are enough and no PoE is needed.",
    },
  },
  // Power supply? None. The switch hangs off the PoE cable of the switch before it — `power: true`
  // means "active device"; where the power comes from is `powerIn`.
  "usw-flex-mini": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "USW Flex Mini (Switch, PoE-gespeist)", en: "USW Flex Mini (switch, PoE-powered)" },
    price: 26,
    ip: "IP20",
    ports: 5,
    sfpPorts: 0,
    poePorts: 0,
    power: true,
    powerIn: "poe",
    sfp: false,
    poe: 0,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/5a176b22-af34-40f2-820c-958610df1825/19394e07-5146-4f8c-b72d-7fdbdf679c97.png",
    url: "switching-utility-poe/products/usw-flex-mini",
    use: {
      de: "Netzwerkports dort verteilen, wo keine Steckdose ist",
      en: "fan out network ports where there is no outlet",
    },
    tags: {
      de: ["Strom aus dem PoE-Kabel", "kein PoE", "5 Ports"],
      en: ["powered over PoE", "no PoE", "5 ports"],
    },
    mount: {
      de: "innen, im Kasten oder hinter dem Gerät",
      en: "indoors, in a box or behind the device",
    },
    note: {
      de: "5-Port-Switch ohne eigenes Netzteil: läuft über ein PoE-Kabel vom vorgeschalteten Switch oder Injektor (oder per 5-V-USB-C). Kein PoE-Ausgang — nur zum Verteilen von Netzwerkports dort, wo keine Steckdose ist.",
      en: "5-port switch with no mains adapter of its own: runs off a PoE cable from an upstream switch or injector (or 5V USB-C). No PoE output — only for fanning out network ports where there is no outlet.",
    },
  },
  "usw-flex-xg": {
    kind: "device",
    vendor: "ubiquiti",
    name: {
      de: "USW Flex XG (Switch, PoE-gespeist, 10G)",
      en: "USW Flex XG (switch, PoE-powered, 10G)",
    },
    price: 270,
    ip: "IP20",
    ports: 5,
    sfpPorts: 0,
    poePorts: 0,
    power: true,
    powerIn: "poe",
    sfp: false,
    poe: 0,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/61d6b40e-0997-4ce0-b723-bb0c2c4aafa2/9d558a4b-49c7-435d-b574-94f6581e23a9.png",
    url: "switching-utility-poe/products/usw-flex-xg",
    use: {
      de: "10G-Ports ohne Steckdose, etwa am Rekorder",
      en: "10G ports with no outlet, at the recorder say",
    },
    tags: {
      de: ["Strom aus dem PoE-Kabel", "kein PoE", "10G"],
      en: ["powered over PoE", "no PoE", "10G"],
    },
    mount: { de: "innen, Tischgerät", en: "indoors, desktop unit" },
    note: {
      de: "Wie der Flex Mini, aber mit Multi-Gigabit-Kupferports (10G/2,5G gemischt) und ebenfalls ohne eigenes Netzteil — läuft über PoE oder USB-C. Kein PoE-Ausgang.",
      en: "Like the Flex Mini, but with multi-gigabit copper ports (10G/2.5G mix) and likewise no mains adapter of its own — runs off PoE or USB-C. No PoE output.",
    },
  },
  "u-poe-plus-plus": {
    kind: "device",
    vendor: "ubiquiti",
    name: { de: "U-PoE++ (90-W-Injektor)", en: "U-PoE++ (90W injector)" },
    price: 25,
    ip: "IP20",
    ports: 1,
    sfpPorts: 0,
    poePorts: 1,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 90,
    dig: false,
    img: "https://cdn.ecomm.ui.com/products/1c303795-9406-459d-bf40-3d7d631ec479/32da745e-e242-4546-ac86-907c88abbca0.png",
    url: "accessories-cables/products/u-poe-plus-plus",
    use: {
      de: "ein einzelnes Gerät mit bis zu 90 W speisen",
      en: "feed a single device with up to 90 W",
    },
    tags: {
      de: ["Strom nötig", "802.3bt", "ein Abgang"],
      en: ["needs power", "802.3bt", "one output"],
    },
    mount: { de: "an der Steckdose, in der Kabelstrecke", en: "at the outlet, inline in the run" },
    note: {
      de: "Günstigster Weg zu 802.3bt-Leistung für ein einzelnes Gerät (bis 60 W) aus einem gewöhnlichen Netzwerkport, wenn kein PoE-Switch mit genug Budget zur Hand ist.",
      en: "The cheapest way to 802.3bt power (up to 60 W) for a single device from an ordinary network port, when no PoE switch with enough budget is on hand.",
    },
  },
  "tplink-poe380s": {
    kind: "device",
    vendor: "tplink",
    name: {
      de: "TP-Link POE380S (PoE++-Injektor, 90 W)",
      en: "TP-Link POE380S (PoE++ injector, 90W)",
    },
    price: 49,
    ip: "IP20",
    ports: 2,
    sfpPorts: 0,
    poePorts: 1,
    power: true,
    powerIn: "mains",
    sfp: false,
    poe: 90,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/POE380S(UN)_1.0_01_large_20231120073148d.jpg",
    url: "https://www.tp-link.com/de/business-networking/omada-accessory-power-poe/poe380s/",
    use: {
      de: "ein PoE++-Gerät mit voller Leistung speisen",
      en: "feed one PoE++ device at full power",
    },
    tags: {
      de: ["Strom nötig", "802.3bt Typ 4", "ein Abgang"],
      en: ["needs power", "802.3bt type 4", "one output"],
    },
    mount: { de: "an der Steckdose, in der Kabelstrecke", en: "at the outlet, inline in the run" },
    note: {
      de: "Speist ein einzelnes Gerät mit bis zu 90 W (802.3bt Typ 4) — die Oberklasse neben dem POE170S (60 W), etwa für PoE++-Kameras mit Heizung oder große PTZ-Modelle.",
      en: "Feeds a single device with up to 90 W (802.3bt Type 4) — the step up from the POE170S (60 W), for PoE++ cameras with heaters or large PTZ models.",
    },
  },
  "trendnet-ti-pg541i": {
    kind: "device",
    vendor: "trendnet",
    name: {
      de: "TRENDnet TI-PG541i (DIN-Schienen-Switch, PoE+)",
      en: "TRENDnet TI-PG541i (DIN-rail switch, PoE+)",
    },
    price: 239,
    ip: "IP30",
    ports: 5,
    sfpPorts: 1,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 120,
    dig: false,
    img: "https://www.trendnet.com/images/products/photos/TI-PG541i_v2.6/TI-PG541i_(v2.xR)_d01_2.webp",
    url: "https://www.trendnet.com/products/PoE/PoE-Switch/TI-PG541i",
    use: {
      de: "PoE-Switch für den Schaltschrank, auf der Hutschiene",
      en: "a PoE switch for the cabinet, on a DIN rail",
    },
    tags: {
      de: ["Strom nötig", "Hutschiene", "−40 bis 70 °C", "1× SFP"],
      en: ["needs power", "DIN rail", "−40 to 70 °C", "1× SFP"],
    },
    mount: { de: "auf der Hutschiene im Schaltschrank", en: "on the DIN rail in a cabinet" },
    note: {
      de: "Industrieausführung fürs Rack oder den Schaltschrank: 4× Gigabit-PoE+ (120 W), 1× Kupfer, 1× SFP, Hutschiene, −40 bis 70 °C, redundante Spannungsversorgung möglich.",
      en: "Industrial version for a rack or cabinet: 4× gigabit PoE+ (120 W), 1× copper, 1× SFP, DIN rail, −40 to 70 °C, redundant power input possible.",
    },
  },
  "trendnet-ti-pg102i": {
    kind: "device",
    vendor: "trendnet",
    name: {
      de: "TRENDnet TI-PG102i (DIN-Schienen-Switch, PoE+, groß)",
      en: "TRENDnet TI-PG102i (DIN-rail switch, PoE+, large)",
    },
    price: 389,
    ip: "IP30",
    ports: 8,
    sfpPorts: 2,
    power: true,
    powerIn: "mains",
    sfp: true,
    poe: 240,
    dig: false,
    img: "https://www.trendnet.com/images/products/photos/TI-PG102i_v1-4/TI-PG102i_V1.4R_d01_2.webp",
    url: "https://www.trendnet.com/products/PoE/PoE-Switch/TI-PG102i",
    use: {
      de: "viele PoE-Geräte aus einem Schaltschrank versorgen",
      en: "feed many PoE devices from one cabinet",
    },
    tags: {
      de: ["Strom nötig", "Hutschiene", "240 W PoE", "2× SFP"],
      en: ["needs power", "DIN rail", "240 W PoE", "2× SFP"],
    },
    mount: { de: "auf der Hutschiene im Schaltschrank", en: "on the DIN rail in a cabinet" },
    note: {
      de: "Größere Hutschienen-Ausführung: 8× Gigabit-PoE+ (240 W gesamt) plus 2× SFP, gleiche Industrie-Bauform wie der TI-PG541i. Für einen Schaltschrank mit vielen PoE-Geräten.",
      en: "Larger DIN-rail version: 8× gigabit PoE+ (240 W total) plus 2× SFP, same industrial form factor as the TI-PG541i. For a cabinet with many PoE devices.",
    },
  },
  "tplink-sm321a": {
    kind: "device",
    vendor: "tplink",
    name: {
      de: "TP-Link SM321A (SFP-Modul, BiDi, Singlemode)",
      en: "TP-Link SM321A (SFP module, BiDi, single-mode)",
    },
    price: 24,
    ip: "IP20",
    ports: 0,
    sfpPorts: 0,
    power: false,
    powerIn: "none",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/SM321A_UN_3.30_2310_large_20231030022430j.png",
    url: "https://www.tp-link.com/de/business-networking/omada-accessory-module-cable/sm321a/",
    use: {
      de: "eine Strecke über eine einzige Faser statt über zwei",
      en: "run a link over a single fibre instead of two",
    },
    tags: {
      de: ["kein Strom", "nur mit SM321B", "eine Faser", "20 km"],
      en: ["no power draw", "only with the SM321B", "one strand", "20 km"],
    },
    mount: { de: "steckt im SFP-Schacht des Switches", en: "plugs into the switch's SFP cage" },
    note: {
      de: "1000Base-BX WDM, 20 km, braucht nur eine Faser statt zwei — steckt zusammen mit dem Gegenstück SM321B an den beiden Enden. Spart eine Ader auf langen oder engen Leerrohrstrecken.",
      en: "1000Base-BX WDM, 20 km, needs only one fibre strand instead of two — pairs with its counterpart SM321B at the two ends. Saves a strand on long or tight conduit runs.",
    },
  },
  "tplink-sm321b": {
    kind: "device",
    vendor: "tplink",
    name: {
      de: "TP-Link SM321B (SFP-Modul, BiDi, Singlemode)",
      en: "TP-Link SM321B (SFP module, BiDi, single-mode)",
    },
    price: 24,
    ip: "IP20",
    ports: 0,
    sfpPorts: 0,
    power: false,
    powerIn: "none",
    sfp: true,
    poe: 0,
    dig: false,
    img: "https://static.tp-link.com/upload/image-line/SM321B_UN_3.30_2310_large_20231030022336x.jpg",
    url: "https://www.tp-link.com/de/business-networking/omada-accessory-module-cable/sm321b/",
    use: {
      de: "das Gegenstück am anderen Ende derselben Faser",
      en: "the far end of the same single fibre",
    },
    tags: {
      de: ["kein Strom", "nur mit SM321A", "eine Faser", "20 km"],
      en: ["no power draw", "only with the SM321A", "one strand", "20 km"],
    },
    mount: { de: "steckt im SFP-Schacht des Switches", en: "plugs into the switch's SFP cage" },
    note: {
      de: "Gegenstück zum SM321A — beide zusammen ersetzen ein normales SFP-Paar auf einer einzelnen Faser. Ohne das jeweils andere Ende bleibt die Strecke dunkel.",
      en: "Counterpart to the SM321A — together they replace a normal SFP pair on a single fibre. Without its matching far end, the run stays dark.",
    },
  },
};

// A junction is a location: `model` is the housing, `gear` are the devices inside it.
// The same map carries both; `kind` tells them apart. `power` used to do that —
// which was wrong as soon as a device needs no power: splice box, surge
// protector, SFP module, PoE extender are components, not housings.
export const isHousing = (key: string) => !!JUNCTIONS[key] && JUNCTIONS[key].kind === "housing";

export const isDevice = (key: string) => !!JUNCTIONS[key] && JUNCTIONS[key].kind === "device";

// A conduit is either a **trench** (`kind: "trench"`) — with one to six ducts inside,
// each with **its own type and its own price**, and cables inside the ducts — or a
// **cable run** (`kind: "cable"`): a bundle on a wall, in the basement, across the attic, or
// as an overhead line, with no trench and no duct. That's why duct and cable are separate here:
// a trunk duct can carry two fibre cables that split onto two ducts at the junction
// — nothing gets split (spliced) in the process.
export const PIPES: Record<string, PipeSpec> = {
  dn50: { name: { de: "Leerrohr DN 50", en: "Conduit DN 50" }, m: 1.6 },
  dn63: { name: { de: "Leerrohr DN 63", en: "Conduit DN 63" }, m: 2.2 },
};

export const CABLES: Record<string, CableSpec> = {
  fiber: {
    name: { de: "Glasfaser SM, 4 Fasern", en: "Fibre SM, 4 cores" },
    m: 1.8,
    fixed: 70,
    color: "var(--accent)",
    info: {
      de: "<p><b>Glasfaser Singlemode, 4 Fasern, vorkonfektioniert (LC).</b> Wird als ganzes Kabel durchs Rohr gezogen, an beiden Enden steckt ein SFP-Modul in Switch oder Medienkonverter (die Fixkosten). Länge spielt keine Rolle, Blitz koppelt nicht ein.</p>\n<ul><li>4 Fasern = 2 Verbindungen mit Reserve. Eine Faserpaar je Ziel.</li>\n<li>Nie knicken: Biegeradius mindestens 15× Kabeldurchmesser. Beim Ziehen die Stecker mit Ziehstrumpf schützen.</li>\n<li>Am Abzweig nicht teilen — zwei Ziele heißt zwei Kabel im Stammrohr.</li></ul>",
      en: "<p><b>Single-mode fibre, 4 cores, pre-terminated (LC).</b> Pulled through the pipe as one cable; at both ends an SFP module sits in a switch or media converter (the fixed cost). Length does not matter, lightning does not couple in.</p>\n<ul><li>4 cores = 2 links with a spare. One fibre pair per destination.</li>\n<li>Never kink it: bend radius at least 15× the cable diameter. Protect the connectors with a pulling sock.</li>\n<li>Do not split at a branch — two destinations means two cables in the trunk.</li></ul>",
    },
    note: {
      de: "Vorkonfektioniert LC. Fixkosten je Kabel: 2 SFP-Module. Am Abzweig durchziehen, nicht spleißen.",
      en: "Pre-terminated LC. Fixed cost per cable: 2 SFP modules. Pull it through at a branch, do not splice.",
    },
  },
  cat: {
    name: { de: "Cat6A", en: "Cat6A" },
    m: 0.9,
    fixed: 30,
    max: 90,
    color: "var(--ink-3)",
    info: {
      de: "<p><b>Cat6A, Kupfer.</b> Trägt Daten bis 10 Gbit/s <em>und</em> PoE-Strom im selben Kabel — deshalb das Kabel von Switch zu Kamera oder Access Point.</p>\n<ul><li>Grenze 90 m je Strecke (plus Patchkabel). Darüber: Glasfaser oder ein Switch dazwischen.</li>\n<li>Zwischen Gebäuden koppelt Blitz ein: Überspannungsschutz an beiden Enden (die Fixkosten) — oder gleich Glasfaser.</li>\n<li>Draußen und in Erde nur als Erdkabel-Variante (PE-Mantel, gelfüllt), nicht das Innenkabel.</li></ul>",
      en: "<p><b>Cat6A, copper.</b> Carries data up to 10 Gbit/s <em>and</em> PoE power in the same cable — hence the cable from switch to camera or access point.</p>\n<ul><li>Limit 90 m per run (plus patch cords). Beyond that: fibre or a switch in between.</li>\n<li>Between buildings lightning couples in: surge protection at both ends (the fixed cost) — or fibre from the start.</li>\n<li>Outdoors and buried only as the outdoor variant (PE sheath, gel-filled), not the indoor cable.</li></ul>",
    },
    note: {
      de: "Nur bis 90 m und nur mit Überspannungsschutz an beiden Enden (Fixkosten). Zwischen Gebäuden lieber Glasfaser.",
      en: "Only up to 90 m and only with surge protection at both ends (the fixed cost). Between buildings, prefer fibre.",
    },
  },
  power: {
    name: { de: "NYY-J 5×2,5 mm²", en: "NYY-J 5×2.5 mm²" },
    m: 2.6,
    fixed: 0,
    color: "var(--power)",
    info: {
      de: '<p><b>NYY-J 5×2,5 mm² — das deutsche Standard-Erdkabel für 230/400 V.</b> N = Normleitung, Y = PVC-Isolierung, Y = PVC-Mantel, J = mit grün-gelbem Schutzleiter; fünf Adern à 2,5 mm² (L1, L2, L3, N, PE).</p>\n<p><b>Starkstrom?</b> Ja — NYY ist für 0,6/1 kV ausgelegt, Drehstrom 400 V ist sein Alltag. Die Grenze setzt der Querschnitt, nicht der Kabeltyp:</p>\n<table class="cost"><tr><th>Querschnitt</th><th>Sicherung (Erde, grob)</th><th>reicht für</th></tr>\n<tr><td>5×2,5 mm²</td><td>16–20 A</td><td>Werkstatt: Steckdosen, Licht, kleine Maschinen (~11 kW)</td></tr>\n<tr><td>5×4 mm²</td><td>25 A</td><td>Wallbox 11 kW mit Reserve, längere Wege</td></tr>\n<tr><td>5×6 mm²</td><td>32 A</td><td>Wallbox 22 kW, Stall mit Kompressor oder Heizung</td></tr>\n<tr><td>5×10 mm²</td><td>40–50 A</td><td>Nebengebäude als eigener Unterverteiler</td></tr></table>\n<ul><li>Ab 30–40 m Länge zählt der Spannungsfall: eine Stufe größer wählen.</li>\n<li>Eigenes Rohr oder 20 cm Abstand zu Datenkabeln.</li>\n<li>Auslegung, Anschluss, FI und Abnahme macht der Elektriker — der Preis hier ist nur das Kabel.</li></ul>',
      en: '<p><b>NYY-J 5×2.5 mm² — the standard German buried power cable for 230/400 V.</b> N = standard cable, Y = PVC insulation, Y = PVC sheath, J = with green-yellow protective earth; five cores of 2.5 mm² (L1, L2, L3, N, PE).</p>\n<p><b>Three-phase?</b> Yes — NYY is rated 0.6/1 kV, 400 V three-phase is its everyday job. The cross-section sets the limit, not the cable type:</p>\n<table class="cost"><tr><th>Cross-section</th><th>Fuse (buried, rough)</th><th>enough for</th></tr>\n<tr><td>5×2.5 mm²</td><td>16–20 A</td><td>Workshop: sockets, light, small machines (~11 kW)</td></tr>\n<tr><td>5×4 mm²</td><td>25 A</td><td>11 kW wallbox with headroom, longer runs</td></tr>\n<tr><td>5×6 mm²</td><td>32 A</td><td>22 kW wallbox, stable with compressor or heating</td></tr>\n<tr><td>5×10 mm²</td><td>40–50 A</td><td>Outbuilding as its own sub-distribution</td></tr></table>\n<ul><li>From 30–40 m of length voltage drop matters: go one size up.</li>\n<li>Own pipe or 20 cm distance from data cables.</li>\n<li>Sizing, connection, RCD and sign-off are the electrician’s job — the price here is the cable only.</li></ul>',
    },
    note: {
      de: "Erdkabel. Anschluss, FI und Abnahme durch den Elektriker, nicht enthalten.",
      en: "Buried cable. Connection, RCD and sign-off by an electrician, not included.",
    },
  },
};

// Fixed order light → copper → power. It decides how cables are named,
// drawn, and sorted in the cross-section.
export const CABLE_ORDER = ["fiber", "cat", "power"];

// The buttons in the catalog are just templates. After that, every conduit can be
// filled in individually: duct type, ducts in the trench, and per duct the cables inside.
export const CONDUITS: Record<string, CondTemplate> = {
  fiber: {
    kind: "trench",
    name: { de: "Leerrohr DN 50 + Glasfaser", en: "Conduit DN 50 + fibre" },
    ducts: [{ pipe: "dn50", cables: [{ type: "fiber", n: 1 }] }],
  },
  cat: {
    kind: "trench",
    name: { de: "Leerrohr DN 50 + Cat6A", en: "Conduit DN 50 + Cat6A" },
    ducts: [{ pipe: "dn50", cables: [{ type: "cat", n: 1 }] }],
  },
  power: {
    kind: "trench",
    name: { de: "Stromrohr DN 63 + NYY-J", en: "Power conduit DN 63 + NYY-J" },
    ducts: [{ pipe: "dn63", cables: [{ type: "power", n: 1 }] }],
  },
  pipe: {
    kind: "trench",
    name: { de: "Nur Leerrohr (Reserve)", en: "Empty conduit (spare)" },
    ducts: [{ pipe: "dn50", cables: [] }],
  },
  // Cable run: on the wall, in the basement, across the attic, as an overhead line — no trench,
  // no duct, but several cables may share the same bundle.
  cable: {
    kind: "cable",
    name: { de: "Kabel Cat6A (ohne Rohr)", en: "Cat6A cable (no conduit)" },
    ducts: [{ cables: [{ type: "cat", n: 1 }] }],
  },
  "cable-fiber": {
    kind: "cable",
    name: { de: "Glasfaser (ohne Rohr)", en: "Fibre cable (no conduit)" },
    ducts: [{ cables: [{ type: "fiber", n: 1 }] }],
  },
};

export const INFRA: InfraItem[] = [
  {
    id: "ucg",
    role: "router",
    ports: 5,
    sfp: true,
    poe: 30,
    price: 250,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B0FD86XR36",
    url: "unifi-cloud-gateways/collections/cloud-gateway-fiber/products/ucg-fiber",
    img: "https://cdn.ecomm.ui.com/products/48cf74fa-0456-4c5f-bbcc-c1a1ffdc11f9/465257f3-0acc-4a11-bb15-762e7f6c0e9c.png",
    name: { de: "UniFi Cloud Gateway Fiber", en: "UniFi Cloud Gateway Fiber" },
    sub: {
      de: "Router, Controller, Protect-NVR · 2× SFP+",
      en: "Router, controller, Protect NVR · 2× SFP+",
    },
    note: {
      de: "Router, Netzwerk-Controller und Protect-Rekorder in einem Gerät, dazu zwei SFP+-Ports für Glasfaser. Nimmt rund fünf 4K-Kameras auf; der Speicher steckt als NVMe darin.",
      en: "Router, network controller and Protect recorder in one box, plus two SFP+ ports for fibre. Records about five 4K cameras; the storage is an NVMe inside it.",
    },
  },
  // FRITZ!Box instead of a UniFi gateway: router with Wi-Fi but no camera recording — the UNVR stays for that.
  {
    id: "fb7690",
    vendor: "avm",
    role: "router",
    ports: 3,
    sfp: false,
    poe: 0,
    price: 280,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B0D63DSFJ6",
    url: "https://fritz.com/en/products/fritz-box-7690",
    img: "https://fritz.com/cdn/shop/files/fritzbox_7690_dsl_2000x2000px.webp",
    name: { de: "FRITZ!Box 7690", en: "FRITZ!Box 7690" },
    sub: {
      de: "DSL bis 300 Mbit/s, WiFi 7, 2,5 GbE · kein NVR",
      en: "DSL up to 300 Mbit/s, Wi-Fi 7, 2.5 GbE · no NVR",
    },
    note: {
      de: "DSL-Router mit WiFi 7, Telefonie und 2,5-GbE-Port. Zeichnet keine Kameras auf — wer ihn als Router nimmt, braucht für die Kameras zusätzlich einen UNVR.",
      en: "DSL router with Wi-Fi 7, telephony and a 2.5 GbE port. It records no cameras — whoever uses it as the router also needs a UNVR for them.",
    },
  },
  {
    id: "fb5690",
    vendor: "avm",
    role: "router",
    ports: 5,
    sfp: false,
    poe: 0,
    price: 340,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B0D8JCN5P4",
    url: "https://fritz.com/en/products/fritz-box-5690-pro",
    img: "https://fritz.com/cdn/shop/files/fritzbox_5690_pro_fiber_dsl_2000x2000px_de.webp",
    name: { de: "FRITZ!Box 5690 Pro", en: "FRITZ!Box 5690 Pro" },
    sub: {
      de: "Glasfaser (SFP) oder DSL, WiFi 7 Tri-Band · kein NVR",
      en: "Fibre (SFP) or DSL, Wi-Fi 7 tri-band · no NVR",
    },
    note: {
      de: "Router für Glasfaser (SFP) oder DSL, WiFi 7 im Tri-Band. Kein Rekorder: die Aufzeichnung übernimmt ein UNVR.",
      en: "Router for fibre (SFP) or DSL, Wi-Fi 7 tri-band. No recorder: a UNVR does the recording.",
    },
  },
  {
    id: "fb5590",
    vendor: "avm",
    role: "router",
    ports: 4,
    sfp: false,
    poe: 0,
    price: 260,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B09ZD4LFR3",
    url: "https://fritz.com/en/products/fritz-box-5590-fiber",
    img: "https://fritz.com/cdn/shop/files/fritzbox_5590_fiber_fiber_2000x2000px_de.webp",
    name: { de: "FRITZ!Box 5590 Fiber", en: "FRITZ!Box 5590 Fiber" },
    sub: {
      de: "Glasfaser (SFP: AON/GPON/XGS-PON), WiFi 6 · kein NVR",
      en: "Fibre (SFP: AON/GPON/XGS-PON), Wi-Fi 6 · no NVR",
    },
    note: {
      de: "Glasfaser-Router mit SFP-Schacht für AON, GPON und XGS-PON, WiFi 6. Kein Rekorder.",
      en: "Fibre router with an SFP cage for AON, GPON and XGS-PON, Wi-Fi 6. No recorder.",
    },
  },
  {
    id: "fb5530",
    vendor: "avm",
    role: "router",
    ports: 2,
    sfp: false,
    poe: 0,
    price: 187,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B08RB83RZ4",
    url: "https://fritz.com/en/products/fritz-box-5530-fiber-20002960",
    img: "https://fritz.com/cdn/shop/files/fritzbox_5530_fiber_fiber_2000x2000px_de.webp",
    name: { de: "FRITZ!Box 5530 Fiber", en: "FRITZ!Box 5530 Fiber" },
    sub: {
      de: "Glasfaser (SFP), WiFi 6, günstiger · kein NVR",
      en: "Fibre (SFP), Wi-Fi 6, cheaper · no NVR",
    },
    note: {
      de: "Die günstige Glasfaser-FRITZ!Box: SFP-Schacht, WiFi 6, weniger Anschlüsse als die 5590. Kein Rekorder.",
      en: "The cheap fibre FRITZ!Box: SFP cage, Wi-Fi 6, fewer ports than the 5590. No recorder.",
    },
  },
  {
    id: "fb6690",
    vendor: "avm",
    role: "router",
    ports: 4,
    sfp: false,
    poe: 0,
    price: 287,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B09P1KD19W",
    url: "https://fritz.com/en/products/fritz-box-6690-cable",
    img: "https://fritz.com/cdn/shop/files/fritzbox_6690_cable_cable_2000x2000px_de.webp",
    name: { de: "FRITZ!Box 6690 Cable", en: "FRITZ!Box 6690 Cable" },
    sub: { de: "Kabel DOCSIS 3.1, WiFi 6 · kein NVR", en: "Cable DOCSIS 3.1, Wi-Fi 6 · no NVR" },
    note: {
      de: "Router für den Kabelanschluss (DOCSIS 3.1) mit WiFi 6. Kein Rekorder.",
      en: "Router for a cable connection (DOCSIS 3.1) with Wi-Fi 6. No recorder.",
    },
  },
  {
    id: "nvme",
    price: 130,
    qty: 1,
    on: false,
    img: "https://cdn.ecomm.ui.com/products/e6ef75f9-b133-46d6-8f52-d8a929bd793c/5f2e437c-b62c-4365-91ce-81c1c7351ef1.png",
    amazon: "https://www.amazon.de/dp/B0DTMH4X6J",
    amazonSimilar: true,
    url: "accessories-network/products/uacc-ssd-tray",
    name: { de: "M.2-Tray + 2 TB NVMe", en: "M.2 tray + 2 TB NVMe" },
    sub: { de: "Aufnahmespeicher im UCG-Fiber", en: "Recording storage inside the UCG Fiber" },
    note: {
      de: "Einschub mit NVMe-SSD für das UCG Fiber. Ohne ihn hat das Gateway keinen Platz für Aufnahmen.",
      en: "Tray with an NVMe SSD for the UCG Fiber. Without it the gateway has nowhere to record.",
    },
  },
  // Switches now live as elements on the map ("Junction / gear" tool),
  // so it's visible where fibre turns back into copper. That's why here only
  // hidden — otherwise they'd be counted twice.
  {
    id: "flex",
    price: 179,
    qty: 0,
    on: false,
    hidden: true,
    url: "switching-utility-poe/products/usw-flex-2-5g-8-poe",
    name: { de: "USW Flex 2.5G PoE", en: "USW Flex 2.5G PoE" },
    sub: { de: "steht auf der Karte", en: "placed on the map" },
  },
  {
    id: "lite8",
    price: 99,
    qty: 0,
    on: false,
    hidden: true,
    url: "switching-utility-poe/products/usw-lite-8-poe",
    name: { de: "USW Lite 8 PoE", en: "USW Lite 8 PoE" },
    sub: { de: "steht auf der Karte", en: "placed on the map" },
  },
  {
    id: "sfp",
    price: 0,
    qty: 0,
    on: false,
    hidden: true,
    name: { de: "Singlemode-SFP-Modul", en: "Single-mode SFP module" },
    sub: { de: "wird über die Kanäle gezählt", en: "counted through the conduits" },
  },
  {
    id: "unvr",
    price: 269,
    qty: 1,
    on: false,
    amazon: "https://www.amazon.de/dp/B08CT8QGWK",
    url: "network-video-recorders/products/unvr",
    img: "https://cdn.ecomm.ui.com/products/8a3b51c6-d3e9-4ea7-95b3-49a1253c4542/1d0a75b2-8096-4e1a-be7f-b3e57c681322.png",
    name: { de: "UNVR (separater Recorder)", en: "UNVR (separate recorder)" },
    sub: { de: "ab 6× 4K empfohlen · 4 HDD-Schächte", en: "recommended from 6× 4K · 4 HDD bays" },
    note: {
      de: "Eigener Rekorder mit vier Festplattenschächten. Nötig, sobald kein UniFi-Gateway aufzeichnet oder mehr als rund fünf 4K-Kameras laufen.",
      en: "A recorder of its own with four drive bays. Needed as soon as no UniFi gateway records, or more than about five 4K cameras run.",
    },
  },
  {
    id: "hdd",
    vendor: "any",
    price: 110,
    qty: 1,
    on: false,
    img: "https://c1.neweggimages.com/productimage/nb640/22-179-014-V01.jpg",
    amazon: "https://www.amazon.de/dp/B01LOOJ8UI",
    url: "https://www.newegg.com/seagate-skyhawk-st4000vx007-4tb/p/N82E16822179014",
    name: { de: "HDD 4 TB (Surveillance)", en: "HDD 4 TB (surveillance)" },
    sub: { de: "für UNVR", en: "for the UNVR" },
    note: {
      de: "Festplatte der Surveillance-Klasse — auf Dauerschreiben ausgelegt, nicht auf Tempo. 4 TB tragen grob zwei 4K-Kameras über 30 Tage Daueraufnahme.",
      en: "A surveillance-class drive — built for continuous writing, not for speed. 4 TB carries roughly two 4K cameras over 30 days of continuous recording.",
    },
  },
  {
    id: "misc",
    vendor: "any",
    price: 120,
    qty: 1,
    on: false,
    name: { de: "Kleinmaterial", en: "Small parts" },
    sub: {
      de: "Dosen, Einführungen, Cat6A innen, Halterungen",
      en: "boxes, entries, indoor Cat6A, brackets",
    },
    note: {
      de: "Sammelposten für Dosen, Kabeleinführungen, kurze Cat6A-Strecken im Gebäude, Halterungen und Überspannungsschutz an Kupfer zwischen Gebäuden.",
      en: "A catch-all for outlets, cable entries, short indoor Cat6A runs, brackets and surge protection on copper between buildings.",
    },
  },
  {
    id: "irflood",
    price: 115,
    qty: 1,
    on: false,
    img: "https://cdn.ecomm.ui.com/products/f2c1e677-1152-4918-9e77-5aae5f7d8987/2ab52b94-5c31-4ec4-9b76-c324fdb2d622.png",
    url: "accessories-camera/collections/camera-vision-enhancers/products/uacc-g6-180-enhancer",
    name: { de: "G6 180 Zusatz-IR-Modul", en: "G6 180 add-on IR module" },
    sub: { de: "verlängert die Nachtsicht der 180er", en: "extends the night vision of the 180" },
    note: {
      de: "Zusätzlicher IR-Strahler für die G6 180. Deren eingebaute Nachtsicht reicht nur 20 m.",
      en: "An extra IR illuminator for the G6 180. Its built-in night vision only reaches 20 m.",
    },
  },
];

// Product link: `url` in the catalog is the verified path in the UniFi EU store.
// If missing (shaft, duct, small parts), only the retailer search remains.
const UI_STORE = "https://eu.store.ui.com/eu/en/category/";

// Third-party manufacturers carry an absolute address; only UniFi paths get completed.
export const productUrl = (m: Model) =>
  m && m.url ? (/^https?:/.test(m.url) ? m.url : UI_STORE + m.url) : null;

// Amazon sits next to the manufacturer page. Where no original item is listed,
// the title says so — otherwise someone might buy the wrong thing in good faith.
export const amazonLabel = (m: Model) =>
  t(m && m.amazonSimilar ? "product.amazon.similar" : "product.amazon");

// "Amazon" in the retailer list leads straight to the verified item if the catalog
// knows one — otherwise to search. A separate button next to it was one too many.
export const shopHref = (sh: Shop, name: string, amazon?: string) =>
  sh.label === "Amazon" && amazon ? amazon : sh.url(name);

export const vendorOf = (m: Model): string => (m && m.vendor) || "ubiquiti";

export const VENDORS: Record<string, string> = {
  ubiquiti: "UniFi",
  reolink: "Reolink",
  netatmo: "Netatmo",
  tplink: "TP-Link",
  mikrotik: "MikroTik",
  avm: "AVM FRITZ!",
  trendnet: "TRENDnet",
  digitus: "DIGITUS",
};

// "any" = manufacturer-neutral (shaft, box, cabinet): passes through every manufacturer filter.
export const isVendor = (m: Model, v: string) => vendorOf(m) === v || m.vendor === "any";

export const SHOPS: Shop[] = [
  { label: "Geizhals", url: (q: string) => "https://geizhals.de/?fs=" + encodeURIComponent(q) },
  {
    label: "Idealo",
    url: (q: string) =>
      "https://www.idealo.de/preisvergleich/MainSearchProductCategory.html?q=" +
      encodeURIComponent(q),
  },
  { label: "Amazon", url: (q: string) => "https://www.amazon.de/s?k=" + encodeURIComponent(q) },
  {
    label: "eBay",
    url: (q: string) => "https://www.ebay.de/sch/i.html?_nkw=" + encodeURIComponent(q),
  },
  {
    label: "Kleinanzeigen",
    url: (q: string) =>
      "https://www.kleinanzeigen.de/s-suchanfrage.html?keywords=" + encodeURIComponent(q),
  },
];

export const imgUrl = (kind: string, key: string, m?: Model) =>
  (m && m.img) || "/products/" + kind + "-" + key + ".jpg";

// Loose on purpose: the element kind decides which of the three shapes comes
// back, and every caller already branches on it.
export const CATALOG: Record<string, Record<string, Model>> = { cam: CAMS, ap: APS, jb: JUNCTIONS };

// A house node is the connection to the network. The speed depends on the
// connection type, hence the tiers sit directly on the type.
export const WAN: Record<string, WanSpec> = {
  dsl: { name: { de: "DSL", en: "DSL" }, speeds: [10, 15, 25, 50] },
  fiber: { name: { de: "Glasfaser", en: "Fibre" }, speeds: [100, 200, 400, 600, 1000] },
};

export const wanOf = (it: Item) => {
  const w: Partial<NonNullable<Item["wan"]>> = it.wan || {};
  const type = w.type && WAN[w.type] ? w.type : "dsl";
  const speeds = WAN[type].speeds;
  const speed = Number(w.speed);
  return { type, speed: speeds.includes(speed) ? speed : speeds[speeds.length - 1] };
};

export const KIND_PREFIX: Record<string, string> = { cam: "K", ap: "A", jb: "J", hub: "H" };

export function modelOf(it: Item): Model {
  const c = CATALOG[it.kind];
  return c && c[it.model as string];
}

// One datasheet for everything: camera, access point, housing, device, item from the
// hub, and cable. Every ⓘ in the app goes through here — name, properties,
// full text and, where there's something to buy, the product box.
export const catEntry = (kind: string, key: string): Model =>
  kind === "gear"
    ? INFRA.find((x) => x.id === key)
    : kind === "cable"
      ? CABLES[key]
      : kind === "cond"
        ? CONDUITS[key]
        : (CATALOG[kind] || {})[key];
