// Static help texts: the ? dialogue and the catalogue guides.
import type { Txt } from "./types";

// Native <dialog> instead of a hand-rolled overlay.
// Buying advice per tab — lives in the ⓘ dialog, not the panel.
export const GUIDE: Record<string, Txt> = {
  cond: {
    de: '<h3>Rohre</h3>\n<ul>\n<li><b>DN 50</b> (50 mm außen) reicht für ein Glasfaser- und ein Cat-Kabel bequem; <b>DN 63</b>, wenn mehr hinein soll oder ein Reserverohr fehlt. Glatte Innenwand, Zugdraht mitbestellen, Bögen weit — kein 90°-Knick.</li>\n<li><b>Jedes Rohr hat seinen eigenen Typ</b> und seinen eigenen Preis: im selben Graben darf ein DN 63 für Strom neben einem DN 50 für Daten liegen. Der Graben selbst kostet die Erdarbeit, je Meter einmal.</li>\n<li><b>Kabel ohne Rohr</b> ist eine eigene Art (Werkzeug „Kabel“, C): ein Kabelzug an der Wand, im Keller, über den Dachboden oder als Freileitung — kein Graben, keine Erdarbeit, aber mehrere Kabel dürfen im selben Bündel liegen. Erdkabel direkt in Sand gehört auch hierher: nur für Strom (NYY) und nur, wenn nie wieder etwas nachgezogen werden soll.</li>\n<li><b>Zwei Rohre, ein Graben:</b> Strom und Daten getrennt führen. Auf der Karte: „Rohre“ hochsetzen — der Strich wird breiter mit heller Mittellinie.</li>\n</ul>\n<h3>Kabel</h3>\n<ul>\n<li><b>Glasfaser SM, 4 Fasern:</b> Singlemode-Kabel, vorkonfektioniert mit LC-Steckern, wird als Ganzes durchgezogen. Braucht an beiden Enden ein SFP-Modul (Fixkosten). Länge ist praktisch egal, kein Blitzschutz nötig — Glas leitet nicht.</li>\n<li><b>Cat6A:</b> Kupfer-Netzwerkkabel, trägt Daten <em>und</em> PoE-Strom. Grenze 90 m. Zwischen Gebäuden nur mit Überspannungsschutz an beiden Enden (Blitz koppelt in Kupfer ein) — deshalb dort lieber Glasfaser.</li>\n<li><b>NYY-J 5×2,5 mm²:</b> das deutsche Standard-Erdkabel für 230/400 V, auch Drehstrom (0,6/1 kV). Für mehr Leistung größerer Querschnitt — Tabelle beim ⓘ am Kabel. N = Normleitung, Y = PVC-Isolierung, Y = PVC-Mantel, J = mit grün-gelbem Schutzleiter; 5 Adern à 2,5 mm² (Drehstrom oder zwei Stromkreise). Anschluss, FI und Abnahme macht der Elektriker.</li>\n</ul>\n<h3>Graben</h3>\n<ul>\n<li>60–80 cm tief, 10 cm Sandbett unten und oben, dann Trassenwarnband, dann Aushub. Unter Fahrwegen tiefer und mit Rohr.</li>\n<li>Strom und Datenkabel im selben Graben, aber in getrennten Rohren oder mit 20 cm Abstand.</li>\n<li>Jeder Richtungswechsel ist eine Ziehstelle: Schacht oder Dose setzen, nicht um die Ecke ziehen.</li>\n</ul>\n<p class="tip">Glasfaser wird am Abzweig nicht geteilt. Zwei Ziele = zwei Kabel im Stammrohr; am Faserende steht ein Switch oder Medienkonverter.</p>',
    en: '<h3>Pipes</h3>\n<ul>\n<li><b>DN 50</b> (50 mm outer) comfortably takes one fibre and one Cat cable; <b>DN 63</b> when more has to go in or there is no spare pipe. Smooth bore, order a draw wire, wide bends — never a 90° elbow.</li>\n<li><b>Every pipe has its own type</b> and its own price: in the same trench a DN 63 for power may sit next to a DN 50 for data. The trench itself costs the earthwork, once per metre.</li>\n<li><b>Cable without a conduit</b> is a kind of its own (the “Cable” tool, C): a run along a wall, through the cellar, across the loft or overhead — no trench, no earthwork, but several cables may share one bundle. Buried cable straight into sand belongs here too: power (NYY) only, and only if nothing will ever be pulled again.</li>\n<li><b>Two pipes, one trench:</b> keep power and data apart. On the map: raise “pipes” — the line gets wider with a light lane in the middle.</li>\n</ul>\n<h3>Cables</h3>\n<ul>\n<li><b>Fibre SM, 4 cores:</b> single-mode cable, pre-terminated with LC connectors, pulled through as one piece. Needs an SFP module at each end (the fixed cost). Length hardly matters, no lightning protection needed — glass does not conduct.</li>\n<li><b>Cat6A:</b> copper network cable, carries data <em>and</em> PoE power. Limit 90 m. Between buildings only with surge protection at both ends (lightning couples into copper) — hence fibre is preferred there.</li>\n<li><b>NYY-J 5×2.5 mm²:</b> the standard German buried power cable for 230/400 V, three-phase included (0.6/1 kV). More power needs a larger cross-section — see the table behind ⓘ at the cable. N = standard cable, Y = PVC insulation, Y = PVC sheath, J = with green-yellow protective earth; 5 cores of 2.5 mm² (three-phase or two circuits). Connection, RCD and sign-off are the electrician’s job.</li>\n</ul>\n<h3>Trench</h3>\n<ul>\n<li>60–80 cm deep, 10 cm of sand below and above, then warning tape, then backfill. Deeper and in a pipe under driveways.</li>\n<li>Power and data cables in the same trench, but in separate pipes or 20 cm apart.</li>\n<li>Every change of direction is a pulling point: set a shaft or box, do not pull around the corner.</li>\n</ul>\n<p class="tip">Fibre is not split at a branch. Two destinations = two cables in the trunk; a switch or media converter sits at the fibre end.</p>',
  },
  cam: {
    de: '<h3>Worauf es ankommt</h3>\n<ul>\n<li><b>Auflösung.</b> 4K (8 MP) erkennt Gesichter und Kennzeichen bis etwa 10–15 m; 2K/5 MP reicht für Übersicht und Nebeneingänge. Mehr Pixel heißt auch mehr Speicher und mehr Last auf dem Rekorder.</li>\n<li><b>Sichtfeld.</b> 80–90° ist „normal“ und trägt weit; ab 105° wird es breit, Details gehen früher verloren. 180° (zwei Sensoren) ist Übersicht ohne Identifikation. PTZ sieht immer nur dorthin, wo sie gerade steht — nie als einzige Kamera.</li>\n<li><b>Nachtsicht.</b> IR ist schwarz-weiß und unsichtbar; Flutlicht/Spotlight liefert Farbe, schreckt ab und blendet Nachbarn. Herstellerangaben sind Bestwerte — real etwa zwei Drittel.</li>\n<li><b>Strom.</b> PoE (802.3af, 15 W) reicht für Bullet, Turret, Dome. PoE+ (802.3at, 30 W) für PTZ, Heizung, Flutlicht; PoE++ (802.3bt) für große PTZ. Ein Cat-Kabel trägt Strom und Bild — deshalb Cat im Leerrohr. WLAN-Kameras brauchen trotzdem eine Steckdose.</li>\n<li><b>Gehäuse.</b> Außen IP66/IP67, IK10 nur dort, wo jemand zuschlagen kann. Turret und Dome unter Vordach oder Decke; Bullet mit Sonnenblende freistehend.</li>\n<li><b>Aufzeichnung.</b> UniFi läuft in Protect auf UNVR, UCG oder UDM — ohne Abo. Reolink zeichnet auf eigenem NVR oder SD auf; per ONVIF/RTSP auch in Protect (nur Bild, keine Protect-Erkennung). Netatmo speichert auf SD und in die App — kein NVR, kein ONVIF, nicht mischbar.</li>\n</ul>\n<h3>Hersteller</h3>\n<ul>\n<li><b>UniFi.</b> Ein System: Kameras, Switches, Rekorder, eine Oberfläche, beste Erkennung. Dafür der höchste Preis je Kamera und nur mit UniFi-Rekorder.</li>\n<li><b>Reolink.</b> Etwa der halbe Preis bei ähnlicher Bildqualität, offen (ONVIF, RTSP), eigener NVR günstig. App und Erkennung weniger poliert. Nur PoE-Modelle nehmen — keine 12-V-Varianten mit Netzteil.</li>\n<li><b>Netatmo.</b> Smart-Home-Kamera: ersetzt die Außenleuchte an der Haustür, Gesichtserkennung, kein Abo. Gut für ein einzelnes Gerät, nicht für ein Kamerasystem mit Rekorder.</li>\n</ul>\n<p class="tip">Faustregel: Übersicht mit wenigen breiten Kameras, dazu je eine „normale“ auf jeden Zugang (Tor, Haustür, Hof). Zoom oder PTZ erst, wenn es eine konkrete Stelle gibt, die man heranholen muss.</p>',
    en: '<h3>What matters</h3>\n<ul>\n<li><b>Resolution.</b> 4K (8 MP) identifies faces and plates out to roughly 10–15 m; 2K/5 MP is enough for overview and side doors. More pixels also means more storage and more load on the recorder.</li>\n<li><b>Field of view.</b> 80–90° is “normal” and carries far; from 105° it gets wide and detail fades sooner. 180° (two sensors) is overview without identification. A PTZ only ever sees where it happens to point — never as the only camera.</li>\n<li><b>Night vision.</b> IR is black-and-white and invisible; a floodlight or spotlight gives colour, deters, and dazzles the neighbours. Manufacturer ranges are best case — count on two thirds.</li>\n<li><b>Power.</b> PoE (802.3af, 15 W) covers bullet, turret and dome. PoE+ (802.3at, 30 W) for PTZ, heaters, floodlights; PoE++ (802.3bt) for large PTZ. One Cat cable carries power and video — hence Cat in the conduit. Wi-Fi cameras still need a socket.</li>\n<li><b>Housing.</b> Outdoors IP66/IP67; IK10 only where someone can reach and hit it. Turret and dome under eaves or a ceiling; a bullet with its sunshade stands free.</li>\n<li><b>Recording.</b> UniFi runs in Protect on a UNVR, UCG or UDM — no subscription. Reolink records to its own NVR or SD; via ONVIF/RTSP also into Protect (video only, no Protect detections). Netatmo records to SD and the app — no NVR, no ONVIF, cannot be mixed.</li>\n</ul>\n<h3>Vendors</h3>\n<ul>\n<li><b>UniFi.</b> One system: cameras, switches, recorder, one interface, the best detection. Highest price per camera and only with a UniFi recorder.</li>\n<li><b>Reolink.</b> About half the price for similar image quality, open (ONVIF, RTSP), cheap own NVR. App and detection less polished. Take PoE models only — no 12 V variants with a power brick.</li>\n<li><b>Netatmo.</b> Smart-home camera: replaces the outdoor light at the front door, face recognition, no subscription. Good for a single device, not for a camera system with a recorder.</li>\n</ul>\n<p class="tip">Rule of thumb: overview with a few wide cameras, plus one “normal” camera on every access (gate, front door, yard). Zoom or PTZ only once there is a specific spot that has to be pulled in.</p>',
  },
  ap: {
    de: '<h3>Worauf es ankommt</h3>\n<ul>\n<li><b>Wi-Fi 7 gegen Wi-Fi 6.</b> Die Reichweite ist praktisch gleich. Der Unterschied ist Durchsatz nahe am Gerät und das 6-GHz-Band — das trägt kurz und ist nur innen sinnvoll. Draußen zählen 2,4 GHz und das Gehäuse.</li>\n<li><b>Reichweite.</b> Freifeld 30–50 m, jede Wand halbiert. Lieber zwei kleine APs als ein starker: Sendeleistung runter, Kanäle trennen. Auf 2,4 GHz nur 1, 6 und 11.</li>\n<li><b>Kabel schlägt Mesh.</b> Wo Cat liegt, immer per Kabel anbinden — ein Mesh-Backhaul frisst die Hälfte der Bandbreite und die Hälfte der Stabilität.</li>\n<li><b>PoE.</b> Innen-APs laufen mit 802.3af, Außen-APs brauchen 802.3at. Der Switch am anderen Ende muss das liefern.</li>\n<li><b>Bauform.</b> Rundstrahler an Decke oder Außenwand für Hof und Weide; Richtantenne, wenn eine Seite gezielt weit abgedeckt werden soll (Stall, Feldweg).</li>\n</ul>\n<h3>Hersteller</h3>\n<ul><li><b>UniFi / TP-Link Omada / MikroTik:</b> PoE-APs für Decke oder Außenwand, ein Kabel für Strom und Daten, Controller-Verwaltung. Innerhalb eines Herstellers bleiben.</li><li><b>AVM FRITZ!:</b> Repeater als AP an der Steckdose, per LAN an die FRITZ!Box. Bequem, wenn die FRITZ!Box ohnehin der Router ist; kein PoE, nichts für draußen, keine Kamera-Aufzeichnung.</li><li>Reolink und Netatmo bauen keine Access Points.</li></ul>\n<p class="tip">Ein AP je Etage oder Gebäudeteil innen, ein Außen-AP je Hofseite — und Kabel dorthin, wo er hängt.</p>',
    en: '<h3>What matters</h3>\n<ul>\n<li><b>Wi-Fi 7 vs Wi-Fi 6.</b> Range is practically the same. The difference is throughput close to the device and the 6 GHz band — short reach, only useful indoors. Outdoors, 2.4 GHz and the housing decide.</li>\n<li><b>Range.</b> Free field 30–50 m, every wall halves it. Two small APs beat one strong one: turn power down, separate channels. On 2.4 GHz use only 1, 6 and 11.</li>\n<li><b>Cable beats mesh.</b> Wherever Cat is laid, wire it — a mesh backhaul eats half the bandwidth and half the stability.</li>\n<li><b>PoE.</b> Indoor APs run on 802.3af, outdoor APs need 802.3at. The switch at the other end has to deliver it.</li>\n<li><b>Form factor.</b> Omnidirectional on a ceiling or outside wall for yard and paddock; directional when one side must be covered far and on purpose (stable, track).</li>\n</ul>\n<h3>Vendors</h3>\n<ul><li><b>UniFi / TP-Link Omada / MikroTik:</b> PoE APs for ceiling or outside wall, one cable for power and data, controller management. Stay within one vendor.</li><li><b>AVM FRITZ!:</b> repeaters as APs at a socket, wired to the FRITZ!Box. Convenient if the FRITZ!Box is the router anyway; no PoE, nothing for outdoors, no camera recording.</li><li>Reolink and Netatmo do not make access points.</li></ul>\n<p class="tip">One AP per floor or wing indoors, one outdoor AP per yard side — and a cable to wherever it hangs.</p>',
  },
  hub: {
    de: "<h3>Was in die Zentrale geh\u00f6rt</h3>\n<ul>\n<li><b>Ein Router.</b> Er bringt den Anschluss ins Haus und vergibt die Adressen — ohne ihn kommt weder Kupfer noch Glasfaser an. Ein Router je Plan.</li>\n<li><b>Glasfaser braucht einen SFP-Port.</b> Entweder im Router (beim UCG Fiber l\u00e4sst sich einer der beiden SFP+ auf LAN umstellen; bei jeder FRITZ!Box ist der SFP-Schacht der <em>WAN</em>-Anschluss), oder in einem Switch mit SFP, oder \u00fcber einen Medienkonverter davor.</li>\n<li><b>Medienkonverter arbeiten in beide Richtungen.</b> Einer je Faserende — au\u00dfer das Ger\u00e4t dort hat selbst einen SFP-Schacht. Je Faserkabel stecken zwei SFP-Module, die rechnet der Kanal schon mit.</li>\n<li><b>Ein PoE-Switch,</b> sobald Kameras oder Access Points direkt an der Zentrale h\u00e4ngen. Das UCG Fiber gibt 30 W ab, das reicht f\u00fcr genau eine Kamera; alles dar\u00fcber braucht einen Switch.</li>\n<li><b>Ein Rekorder.</b> Das UCG Fiber zeichnet selbst auf (rund f\u00fcnf 4K-Kameras). Mit einer FRITZ!Box als Router braucht es zus\u00e4tzlich einen UNVR — sie zeichnet nichts auf.</li>\n<li><b>\u00dcberspannungsschutz</b> an jedem Kupferkabel, das von drau\u00dfen hereinkommt. Zwischen Geb\u00e4uden lieber gleich Glasfaser: die tr\u00e4gt keinen Blitz herein.</li>\n</ul>",
    en: "<h3>What belongs in the head end</h3>\n<ul>\n<li><b>A router.</b> It brings the line into the building and hands out addresses — without one neither copper nor fibre arrives. One router per plan.</li>\n<li><b>Fibre needs an SFP port.</b> Either in the router (on the UCG Fiber one of the two SFP+ can be switched to LAN; on every FRITZ!Box the SFP cage is the <em>WAN</em> port), or in a switch with SFP, or through a media converter in front of it.</li>\n<li><b>Media converters work both ways.</b> One per fibre end — unless the device there has an SFP cage of its own. Every fibre cable carries two SFP modules, and the conduit already counts them.</li>\n<li><b>A PoE switch</b> as soon as cameras or access points hang straight off the head end. The UCG Fiber hands out 30 W, enough for exactly one camera; anything more needs a switch.</li>\n<li><b>A recorder.</b> The UCG Fiber records by itself (about five 4K cameras). With a FRITZ!Box as the router you also need a UNVR — it records nothing.</li>\n<li><b>Surge protection</b> on every copper cable coming in from outside. Between buildings prefer fibre: it carries no lightning indoors.</li>\n</ul>",
  },
  gear: {
    de: '<h3>Router und Rekorder</h3>\n<ul>\n<li><b>UniFi Cloud Gateway Fiber:</b> Router, Netzwerk-Controller und Protect-Rekorder in einem Gerät, mit zwei SFP+-Ports. Ein Kasten für alles — vorausgesetzt, die Kameras kommen von UniFi.</li>\n<li><b>FRITZ!Box:</b> Router mit WLAN und Telefonie, aber ohne jede Kamera-Aufzeichnung. Wer sie als Router nimmt, braucht für die Kameras zwingend einen UNVR daneben.</li>\n<li><b>UNVR:</b> eigener Rekorder mit vier Plattenschächten. Nötig ab etwa sechs 4K-Kameras, bei langer Vorhaltezeit — oder eben immer dann, wenn kein UniFi-Gateway im Plan steht.</li>\n</ul>\n<h3>Speicher</h3>\n<ul>\n<li>Faustregel je 4K-Kamera: <b>1 bis 1,5 TB im Monat</b> bei Daueraufnahme. Nur bei Bewegung aufzuzeichnen drückt das auf etwa ein Drittel.</li>\n<li>Vorhaltezeit festlegen, dann rechnen: 30 Tage sind der übliche Ansatz. Vier 4K-Kameras, 30 Tage, Bewegung — das sind rund 2 TB.</li>\n<li>Platten der <b>Surveillance-Klasse</b> nehmen (WD Purple, Seagate SkyHawk). Sie sind auf Dauerschreiben ausgelegt, Desktop-Platten gehen daran kaputt.</li>\n</ul>\n<h3>Kleinmaterial</h3>\n<ul>\n<li>Dosen, Kabeleinführungen, kurze Cat6A-Strecken im Gebäude und Halterungen tauchen auf jeder Rechnung auf — und in keiner Planung.</li>\n<li><b>Überspannungsschutz</b> an jedem Kupferkabel, das zwischen zwei Gebäuden läuft, und zwar an beiden Enden. Glasfaser braucht ihn nicht.</li>\n</ul>\n<h3>Am Abzweigpunkt</h3>\n<ul>\n<li><b>Faser weiterverteilen:</b> ein Switch mit zwei oder mehr SFP-Sch\u00e4chten nimmt die ankommende Faser an und gibt weitere Fasern ab — gespleißt wird dabei nichts.</li>\n<li><b>Strom im Schacht:</b> Switch, Medienkonverter und Injektor haben ein eigenes Netzteil und brauchen dort 230 V. Entweder ein NYY-J im selben Graben — oder ein PoE-gespeistes Ger\u00e4t, das am Netzwerkkabel h\u00e4ngt.</li>\n</ul>\n<p class="tip">Diese Teile stehen nicht auf der Karte. Ein Klick im Katalog zählt ein Stück hoch, die Menge steht danach im Auswahl-Panel.</p>',
    en: '<h3>Router and recorder</h3>\n<ul>\n<li><b>UniFi Cloud Gateway Fiber:</b> router, network controller and Protect recorder in one box, with two SFP+ ports. One box for everything — as long as the cameras are UniFi.</li>\n<li><b>FRITZ!Box:</b> a router with Wi-Fi and telephony, but no camera recording at all. Using one as the router makes a UNVR mandatory for the cameras.</li>\n<li><b>UNVR:</b> a recorder of its own with four drive bays. Needed from about six 4K cameras, with long retention — or simply whenever no UniFi gateway is in the plan.</li>\n</ul>\n<h3>Storage</h3>\n<ul>\n<li>Rule of thumb per 4K camera: <b>1 to 1.5 TB a month</b> when recording continuously. Recording on motion only brings that down to roughly a third.</li>\n<li>Decide the retention first, then do the maths: 30 days is the usual figure. Four 4K cameras, 30 days, motion only — about 2 TB.</li>\n<li>Use <b>surveillance-class</b> drives (WD Purple, Seagate SkyHawk). They are built for continuous writing; desktop drives die of it.</li>\n</ul>\n<h3>Small parts</h3>\n<ul>\n<li>Outlets, cable entries, short indoor Cat6A runs and brackets show up on every invoice — and in no plan.</li>\n<li><b>Surge protection</b> on every copper cable that runs between two buildings, at both ends. Fibre does not need it.</li>\n</ul>\n<h3>At a junction point</h3>\n<ul>\n<li><b>Passing fibre on:</b> a switch with two or more SFP cages takes the incoming fibre and hands further fibres out — nothing is spliced.</li>\n<li><b>Power in a shaft:</b> a switch, media converter or injector carries its own mains adapter and needs 230 V there. Either an NYY-J in the same trench — or a PoE-powered device that hangs on the network cable.</li>\n</ul>\n<p class="tip">These parts are not on the map. A click in the catalogue counts one more; the quantity then sits in the selection panel.</p>',
  },
};

// Quick guide inside the app. The long version lives at /help — both texts
// must be updated together whenever the controls change.
type HelpSection = [string, [string, string][]];

export const HELP: HelpSection[] = [
  [
    "help.tools",
    [
      ["V", "help.tool.select"],
      ["K", "help.tool.cam"],
      ["A", "help.tool.ap"],
      ["J", "help.tool.jb"],
      ["H", "help.tool.hub"],
      ["L", "help.tool.cond"],
      ["C", "help.tool.cable"],
    ],
  ],
  [
    "help.keys",
    [
      ["Strg+Z / Strg+Y", "help.key.undo"],
      ["Entf", "help.key.del"],
      ["Esc", "help.key.esc"],
      ["⏎", "help.key.enter"],
    ],
  ],
  [
    "help.tips",
    [
      ["", "help.tip.vtx"],
      ["", "help.tip.snap"],
      ["", "help.tip.cross"],
      ["", "help.tip.cluster"],
      ["", "help.tip.back"],
      ["", "help.tip.fiber"],
      ["", "help.tip.link"],
      ["", "help.tip.jb"],
      ["", "help.tip.hub"],
      ["", "help.tip.gear"],
      ["", "help.tip.info"],
      ["", "help.tip.share"],
      ["", "help.tip.export"],
      ["", "help.tip.show"],
      ["", "help.tip.look"],
      ["", "help.tip.layout"],
    ],
  ],
];
